### PR TITLE
Separate importing logic for files and services

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Treat importing files and services differently
Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/868
## Testing

Manually
## Documentation

NA
## Checklist

- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/259)

### CODE REVIEW

**Comment by james-rae** [comment]
I've made my comments non-blocking so you can finish this PR tomorrow

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/layer.js, line 262 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-Kr7kKXiH2rieNkAuSNM:-Kr7kKXjBHWYZIMOuLto:byts0dx) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/f701d0be451be7d0588d5cc0f656888f3f7ac861/src/layer.js#L262)):*
> ```JavaScript
> // - serviceType : the type of file (CSV, Shape, GeoJSON, Unknown)
> // - fileData : if the file is located on a server, will xhr
> function pokeFile(url, hint) {
> ```

can we keep the hint?  it's good to have in case we need to start doing overrides / trickery.  add it to `predictFileUrlBuilder` guts too

---

*[src/layer.js, line 325 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-Kr7kZb-3iKmbYrx9F4q:-Kr7kZb-3iKmbYrx9F4r:b-k8vd3x) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e9b38d2713e77c6d3599b3cf5066cea1988188b0/src/layer.js#L325)):*
> ```JavaScript
>  /**
>   * function predictFileUrlBuilder
>   * @method predictLayerUrl
> ```

wrong name

---

*[src/layer.js, line 377 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-Kr7kAAjbP4zLpnzRIag:-Kr7kAAjbP4zLpnzRIah:b-t7aue8) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e9b38d2713e77c6d3599b3cf5066cea1988188b0/src/layer.js#L377)):*
> ```JavaScript
> 
>             // hint type to hint flavour
>             hintToFlavour[serviceType.CSV] = 'F_FILE';
> ```

remove the file based things here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-:-Kr7kc-rCyXq2AU1SUwS:b-rg7ea9)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259)*

**Comment by AleksueiR** [comment]
I think you also need to update tests that run predictions on file urls, ones like here: https://github.com/fgpv-vpgf/geoApi/blob/v2.1.0/test/testUrl.html#L21

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-:-KrAqB7_pMVyzV0qXZ70:b2a4r3p)*

**Comment by barryytm** [comment]
Correct me if I am wrong, I don't think we even use those test files.

**Comment by AleksueiR** [comment]
I'm not sure. James would be able to tell if he uses them or not.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-:-KrBQXDXJ6lZ1dora3M_:bwtpajo)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/layer.js, line 262 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-Kr7kKXiH2rieNkAuSNM:-KrBRIINxy5SR06tdJEa:bdctcrg) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/f701d0be451be7d0588d5cc0f656888f3f7ac861/src/layer.js#L262)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

can we keep the hint?  it's good to have in case we need to start doing overrides / trickery.  add it to `predictFileUrlBuilder` guts too
</blockquote></details>

done, than

---

*[src/layer.js, line 325 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-Kr7kZb-3iKmbYrx9F4q:-KrBRJaeapQf8QkubuWM:b-r18wje) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e9b38d2713e77c6d3599b3cf5066cea1988188b0/src/layer.js#L325)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

wrong name
</blockquote></details>

done, thanks

---

*[src/layer.js, line 377 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-Kr7kAAjbP4zLpnzRIag:-KrBRKz9xvqxx-8R7Zpk:b-r18wje) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e9b38d2713e77c6d3599b3cf5066cea1988188b0/src/layer.js#L377)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

remove the file based things here
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259)*

**Comment by AleksueiR** [comment]
Can you fix them anyway? Shouldn't take long.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-:-KrBRcsTm9acIjscPBhG:b60gmoi)*

**Comment by barryytm** [comment]
done, thanks

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259#-:-KrBSh2YE3gIac0C3oVR:b-lhs69o)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/259)*

**Pull request merged**
