### PR TITLE
Part 1: base map re-projection, full extent, overview map issue. 3rd try

### PR DESCRIPTION
**Pull request by ec-dev**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/90)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mapManager.js, line 114 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/90#-KCwYrKjKi6DwhYLrh8f:-KCwYrKjKi6DwhYLrh8g:-1384637222) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/98df39058588cb4d6696407665693c2218003960/src/mapManager.js#L114)):*
Why is startup being called twice?  Also, shouldn't visibility be exposed as a call for the viewer (the visible property in the config will only contain the value at the start, but if the event is exposed it could be set by the viewer and potentially use angular's binding for state)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/90)*

**Comment by ec-dev** [comment]
*[src/mapManager.js, line 114 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/90#-KCwYrKjKi6DwhYLrh8f:-KCzjfeiDdQvpXRZjqmt:847477855) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/98df39058588cb4d6696407665693c2218003960/src/mapManager.js#L114)):*
missed a line of code, overviewMapCtrl.destroy(); overview map needs to be re-created when selection-change completes; hence the 2nd overviewMapCtrl.startup()

2nd point about the visible property -> good catch. Currently we don't have mechanism to enable and disable the overview map, therefore, I set the visible property based on the config.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/90)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/90)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/90)*

**Pull request merged**
