### PR TITLE
Add smart defaults to service-based feature layer

### PR DESCRIPTION
**Pull request by AleksueiR**
In support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/770

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/131)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layer.js, line 181 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/131#-KLRM88Egj7SvnyZgP6H:-KLRM88Egj7SvnyZgP6I:-1921203058) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/148fe6176af3d3ef51cabaefb766f7abffdd5d8b/src/layer.js#L181)):*
> ```JavaScript
>         info.smartDefaults = {
>             // TODO: try to find a name field if possible
>             primary: info.fields[0].name // pick the first field as primary and return its name for ui binding
> ```

doesn't seem very smart to me, I think we should import a machine learning library and try to figure out what field is most likely to be the best short description field

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/131)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/131)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layer.js, line 181 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/131#-KLRM88Egj7SvnyZgP6H:-KLRMkTfD2Zol64MHLnB:-426611149) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/148fe6176af3d3ef51cabaefb766f7abffdd5d8b/src/layer.js#L181)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> doesn't seem very smart to me, I think we should import a machine learning library and try to figure out what field is most likely to be the best short description field
</details>
Sounds like a student task.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/131)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layer.js, line 181 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/131#-KLRM88Egj7SvnyZgP6H:-KLRMrtnChdO3zPxAetc:-510466975) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/148fe6176af3d3ef51cabaefb766f7abffdd5d8b/src/layer.js#L181)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Sounds like a student task.
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/131)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/131)*

**Pull request merged**
