### PR TITLE
fix JSON indexing in symbology

### PR DESCRIPTION
**Pull request by cynngah**
FGPV has a different format when fetching the legend as compared to the map server. Symbology function broke beacuse was indexing stuff based on map server format, so had to change it to accomodate the FGPV returned format.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/100)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/100)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/100)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/100)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/100)*

**Pull request merged**
