### PR TITLE
test(query): add unit tests for query

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Add unit tests for query
## Testing

Yes, all of the codes are part of unit tests
## Documentation

None
## Checklist

- [x] `gulp test` succeeds without warnings or errors
- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/199)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[spec/querySpec.js, line 8 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkBVOPJYVDs4ucDq4N0:-KkBVOPJYVDs4ucDq4N1:bt2mtwl) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/90a59dc08edc31a1c64f36540649847522279db4/spec/querySpec.js#L8)):*
> ```JavaScript
> // A fake method for QueryTask which is in EsriBundle
> function execute(query, returnFeatureSet, returnError) {
>     returnFeatureSet(query);
> ```

Small functions like these are fine to inline into the code.  Also, feel free to leave off the comment if it takes longer to read (and understand) than the corresponding code.

---

*[spec/querySpec.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkBW8prlgrVc2Up7csk:-KkBW8prlgrVc2Up7csl:b-1ilb16) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/90a59dc08edc31a1c64f36540649847522279db4/spec/querySpec.js#L48)):*
> ```JavaScript
>     var optionsWithFeatureLayer;
>     var optionsWithUrlAndFeatureLayer;
>     let options;
> ```

`options` does not need to be declared at this level, it can be declared once per test and this improves isolation between the tests (e.g. if you write a new test and forget to reinitialize options it will be more obvious than if it runs with the options set by the previous test)

---

*[spec/querySpec.js, line 51 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkBUzKIiX0W7Y5sTr0P:-KkBUzKJEiJIK859SqGn:babssri) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/90a59dc08edc31a1c64f36540649847522279db4/spec/querySpec.js#L51)):*
> ```JavaScript
> 
>     beforeEach(() => {
>         fakeBundle = {
> ```

`fakeBundle` and all the `options*` objects are static and can be pulled out of the `beforeEach` call.  They can also be assigned `const`.

---

*[spec/querySpec.js, line 114 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkBWvFvp7tVHsUwZyQY:-KkBWvFwlt1TwBlxJYPV:b3qj931) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/90a59dc08edc31a1c64f36540649847522279db4/spec/querySpec.js#L114)):*
> ```JavaScript
>         options = optionsWithUrl;
> 
>         spyOn(fakeBundle, 'Query').and.callThrough();
> ```

If the spies are setup for each test you can move them into the `beforeEach` call

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199)*

**Comment by barryytm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[spec/querySpec.js, line 8 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkBVOPJYVDs4ucDq4N0:-KkBpJKA4ihXQxZuQhg6:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/90a59dc08edc31a1c64f36540649847522279db4/spec/querySpec.js#L8)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Small functions like these are fine to inline into the code.  Also, feel free to leave off the comment if it takes longer to read (and understand) than the corresponding code.
</blockquote></details>

Done

---

*[spec/querySpec.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkBW8prlgrVc2Up7csk:-KkBpMNy-mC2HgzHkcUw:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/90a59dc08edc31a1c64f36540649847522279db4/spec/querySpec.js#L48)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

`options` does not need to be declared at this level, it can be declared once per test and this improves isolation between the tests (e.g. if you write a new test and forget to reinitialize options it will be more obvious than if it runs with the options set by the previous test)
</blockquote></details>

Done

---

*[spec/querySpec.js, line 51 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkBUzKIiX0W7Y5sTr0P:-KkBpNF_3CGB4OuWCZn6:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/90a59dc08edc31a1c64f36540649847522279db4/spec/querySpec.js#L51)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

`fakeBundle` and all the `options*` objects are static and can be pulled out of the `beforeEach` call.  They can also be assigned `const`.
</blockquote></details>

Done

---

*[spec/querySpec.js, line 114 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkBWvFvp7tVHsUwZyQY:-KkBpO7YKdLrztP1inIX:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/90a59dc08edc31a1c64f36540649847522279db4/spec/querySpec.js#L114)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

If the spies are setup for each test you can move them into the `beforeEach` call
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[spec/querySpec.js, line 39 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkC2RF3JjG_iQUopaTT:-KkC2RF3JjG_iQUopaTU:bmq5hs7) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4dfc5770e4bb919a97e427593a04a9c43384a373/spec/querySpec.js#L39)):*
> ```JavaScript
>             }
>         }
>     var queryGeo;   // the module
> ```

let (let is generally preferred over var due to the new semantics https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let )

---

*[spec/querySpec.js, line 54 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkC37CecuiKwEtYWNfq:-KkC37Cfq9OxPCCOJenB:b4775z1) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4dfc5770e4bb919a97e427593a04a9c43384a373/spec/querySpec.js#L54)):*
> ```JavaScript
>      */
>     it ('checks whether query atrributes matches options atrributes from the user', (done) => {
>         var options = {
> ```

const (and same for the other two tests)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199)*

**Comment by barryytm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[spec/querySpec.js, line 39 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkC2RF3JjG_iQUopaTT:-KkCFMCx_q2P8NE2El3-:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4dfc5770e4bb919a97e427593a04a9c43384a373/spec/querySpec.js#L39)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

let (let is generally preferred over var due to the new semantics https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let )
</blockquote></details>

done thanks

---

*[spec/querySpec.js, line 54 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199#-KkC37CecuiKwEtYWNfq:-KkCFOY4ef2C0KXSPP7X:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4dfc5770e4bb919a97e427593a04a9c43384a373/spec/querySpec.js#L54)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

const (and same for the other two tests)
</blockquote></details>

done thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/199)*

**Pull request merged**
