### PR TITLE
fix(layer): manage OBJECTID column for geojson object

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
## Description
Data table duplicated OBJECTID column for user added CSV layer fgpv-vpgf/fgpv-vpgf#1449

## Testing
Manual tests with csv and geojson files

## Checklist

- [x] `gulp test` succeeds without warnings or errors
- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version

Closes fgpv-vpgf/fgpv-vpgf#1449

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/177)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/177)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/layer.js, line 744 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/177#-KZNBgkOzmQsaCCBukZ8:-KZNBgkOzmQsaCCBukZ9:bxda52f) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2baf8b18331414eea7de84623f6af0560d7f4eed/src/layer.js#L744)):*
> ```JavaScript
> 
>         // to avoid double OBJECTID columns. Useful for both geojson and CSV file.
>         if ('OBJECTID' in val.properties && typeof val.properties !== 'undefined') {
> ```

`val.properties` cannot be undefined here so only the first part of the if is needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/177)*

**Comment by ChrisLatRNCan** [comment]
*[src/layer.js, line 744 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/177#-KZNBgkOzmQsaCCBukZ8:-KZNJn5ZSnnN7zQFfx0i:bph92ew) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2baf8b18331414eea7de84623f6af0560d7f4eed/src/layer.js#L744)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

`val.properties` cannot be undefined here so only the first part of the if is needed
</blockquote></details>

Totally right. I'll fix that. Thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/177)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/177)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/177)*

**Pull request merged**
