### PR TITLE
feat(layer): calculate smartdefaults for csv import

### PR DESCRIPTION
**Pull request by AleksueiR**
In support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/770

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/128)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layer.js, line 531 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128#-KKxVKiyehPykv0JMp3K:-KKxVKiyehPykv0JMp3L:-1418981184) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/596dcc3943712a49deaaf224504d991dada3aadd/src/layer.js#L531)):*
> ```JavaScript
>                         resolve(res);
>                     } else {
>                         reject(new Error('File has no rows'));
> ```

Not your fault, but this error message looks cut & pasted from above.  Should probably read `File has inconsistent column counts` or something.  Can you sneak it into this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128)*

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layer.js, line 531 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128#-KKxVKiyehPykv0JMp3K:-KKxWIoSARjhPzGXWwZR:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/596dcc3943712a49deaaf224504d991dada3aadd/src/layer.js#L531)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> Not your fault, but this error message looks cut & pasted from above.  Should probably read `File has inconsistent column counts` or something.  Can you sneak it into this PR?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128)*

**Comment by james-rae** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128#-:-KKx_4NtwYwwcx-hbTSi:1417088721)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/layer.js, line 500 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128#-KLGoQmT0ftqWSVx8Pfp:-KLGoQmT0ftqWSVx8Pfq:-93071955) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/65e7ed9d808964cc49f1e1b492db7c436ea4b213/src/layer.js#L500)):*
> ```JavaScript
>     const formattedData = arrayBufferToString(data); // convert from arraybuffer to string to parsed csv. store string format for later
>     const rows = csvPeek(formattedData, ','); // FIXME: this assumes delimiter is a `,`; need validation
>     let errorMesage; // error message if any to return
> ```

typo in var name: errorMessage

---

*[src/layer.js, line 574 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128#-KLGn9r4PkvCUtyget7D:-KLGn9r4PkvCUtyget7E:268289205) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/65e7ed9d808964cc49f1e1b492db7c436ea4b213/src/layer.js#L574)):*
> ```JavaScript
>  * From provided CSV data, guesses which columns are long and lat. If guessing is no successful, returns null for one or both fields.
>  *
>  * @method guessLatLong
> ```

method name differs from declared name

---

*[src/layer.js, line 581 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128#-KLGoE_6-aItueHwICZX:-KLGoE_6-aItueHwICZY:-132991295) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/65e7ed9d808964cc49f1e1b492db7c436ea4b213/src/layer.js#L581)):*
> ```JavaScript
> function guessCSVfields(rows) {
>     // magic regexes
>     const latValueRegex = new RegExp(/^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?)$/i); // filters by field value
> ```

drop ignorecase on numeric regexes
maybe leave a TODO if we notice performance issues on CSV loading

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128)*

**Comment by AleksueiR** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/layer.js, line 500 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128#-KLGoQmT0ftqWSVx8Pfp:-KLGps9JaeNRbAp2ovTx:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/65e7ed9d808964cc49f1e1b492db7c436ea4b213/src/layer.js#L500)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo in var name: errorMessage
</details>
Done.

---

*[src/layer.js, line 574 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128#-KLGn9r4PkvCUtyget7D:-KLGonyo3PFNuTlVa7Xf:2071880877) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/65e7ed9d808964cc49f1e1b492db7c436ea4b213/src/layer.js#L574)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> method name differs from declared name
</details>
Done. Not sure why build didn't catch that.

---

*[src/layer.js, line 581 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128#-KLGoE_6-aItueHwICZX:-KLGpc2KLUiqpSF6r1PM:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/65e7ed9d808964cc49f1e1b492db7c436ea4b213/src/layer.js#L581)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> drop ignorecase on numeric regexes
> maybe leave a TODO if we notice performance issues on CSV loading
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128)*

**Comment by cynngah** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/128)*

**Pull request merged**
