### PR TITLE
Strengthen validation for CSV files

### PR DESCRIPTION
**Pull request by barryytm**
## Description

As title and also get rid of the errors when running unit tests

Relating to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2254, https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2230
## Testing

Yes
## Documentation

Some spec files
## Checklist

- [x] `npm run test` succeeds without warnings or errors
- [ ] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/250)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[spec/attributeSpec.js, line 68 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-KpzrVD2fo1vzrETp2XZ:-KpzrVD2fo1vzrETp2X_:b993u6v) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/59d9af808ccd3b17a56e121d26a37efa704d344b/spec/attributeSpec.js#L68)):*
> ```JavaScript
>     describe('loadServerAttribs', () => {
> 
>         // NOTE: the attributes of the renderer fomr the layer was missing of strange reasons
> ```

Please, add a `FIXME` to restore this test later.

---

*[src/layer.js, line 637 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-KpzqZo3TT5tysoFltzQ:-Kpzq1wS9cNQmTX_M17l:b-axyfmy) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/59d9af808ccd3b17a56e121d26a37efa704d344b/src/layer.js#L637)):*
> ```JavaScript
>  * @return {Object}      an object with lat and long string properties indicating corresponding field names
>  */
> function guessCSVfields(rows, latCandidates, longCandidates) {
> ```

Need to update jsdoc.

---

*[src/layer.js, line 639 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-Kpzr3Vit6YtAMUbHqdZ:-Kpzr3Vit6YtAMUbHqd_:bb1uv29) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/59d9af808ccd3b17a56e121d26a37efa704d344b/src/layer.js#L639)):*
> ```JavaScript
> function guessCSVfields(rows, latCandidates, longCandidates) {
>     // pick the first lat guess or null
>     const lat = latCandidates[0] || null;
> ```

Here, you can try filtering `long/latCandidates` by name.

---

*[src/layer.js, line 671 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-Kpzqc8nj7zFoT-JURYD:-Kpzqc8nj7zFoT-JURYE:b-g2xgjb) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/59d9af808ccd3b17a56e121d26a37efa704d344b/src/layer.js#L671)):*
> ```JavaScript
>             rows.every((row, rowIndex) =>
>                 rowIndex === 0 || valueRegex.test(row[index]))) // skip first row as its just headers
>         .filter(field => nameRegex.test(field));
> ```

Since we are restricting the field list to only fields with valid lat/long values, we can no longer filter by name here, since a valid field might have an arbitrary name which doesn't match our regex.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250)*

**Comment by barryytm** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[spec/attributeSpec.js, line 68 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-KpzrVD2fo1vzrETp2XZ:-Kq3mhHa3rkIu0D88mhF:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/59d9af808ccd3b17a56e121d26a37efa704d344b/spec/attributeSpec.js#L68)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please, add a `FIXME` to restore this test later.
</blockquote></details>

done, thanks

---

*[src/layer.js, line 637 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-KpzqZo3TT5tysoFltzQ:-Kq3miz6c5BjkrmRuJ3e:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/59d9af808ccd3b17a56e121d26a37efa704d344b/src/layer.js#L637)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Need to update jsdoc.
</blockquote></details>

done, thanks

---

*[src/layer.js, line 639 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-Kpzr3Vit6YtAMUbHqdZ:-Kq3mjPeADGOt97pYmMw:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/59d9af808ccd3b17a56e121d26a37efa704d344b/src/layer.js#L639)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Here, you can try filtering `long/latCandidates` by name.
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250)*

**Comment by barryytm** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/layer.js, line 671 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-Kpzqc8nj7zFoT-JURYD:-Kq3mnWPTbLFpqUXQeqo:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/59d9af808ccd3b17a56e121d26a37efa704d344b/src/layer.js#L671)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Since we are restricting the field list to only fields with valid lat/long values, we can no longer filter by name here, since a valid field might have an arbitrary name which doesn't match our regex.
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/layer.js, line 654 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-Kq3vQ_-wJH76mDCUwpQ:-Kq3vQ_-wJH76mDCUwpR:bxq7tr5) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/39faecb112d8cbd24959d2e2da9e5fe74c8fe976/src/layer.js#L654)):*
> ```JavaScript
>     let long = longCandidates.find(field => field !== lat) || null;
>     for (let j in longCandidates) {
>         if (longNameRegex.test(longCandidates[j])) {
> ```

Since `lat` and `long` candidates can overlap, need to check here that `longNameRegex.test(longCandidates[j]) && longCandidates[j] !== lat`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250)*

**Comment by barryytm** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layer.js, line 654 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-Kq3vQ_-wJH76mDCUwpQ:-Kq43dPYcGj5IWKibKYM:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/39faecb112d8cbd24959d2e2da9e5fe74c8fe976/src/layer.js#L654)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Since `lat` and `long` candidates can overlap, need to check here that `longNameRegex.test(longCandidates[j]) && longCandidates[j] !== lat`.
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250#-:-Kq43hw3462KaZf2BqHl:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/250)*

**Pull request merged**
