### PR TITLE
Feature/attributes

### PR DESCRIPTION
**Pull request by james-rae**
The diff looks brutal, but all I've done here is

* hoist functions out of the module exports block, now using builder functions and parameters to access the esriBundle
* change promise code to use `.catch` instead of second function parameter
* change some `let`s to `const`s

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/55)

### CODE REVIEW

**Comment by alyec** [comment]
I added a ton of comments.  Feel free to ignore stuff or turn it into TODOs for after the March release.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/attribute.js, line 16 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tTu8b0RAN3bMHQkNg:-K8tTu8cyD2VzBTrhVsr:-201638898) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L16)):*
how about null (sorry for covering stuff that isn't in the scope of changes)?

---

*[src/attribute.js, line 33 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tV36VJ7jbuxs6YUz7:-K8tV36VJ7jbuxs6YUz8:905760183) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L33)):*
why is this setting properties on the caller's data object?

---

*[src/attribute.js, line 49 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tYE1V-6NY7RWSSln1:-K8tYE1V-6NY7RWSSln2:-470516354) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L49)):*
const

---

*[src/attribute.js, line 68 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tafqedjD8oHVikGpz:-K8tafqedjD8oHVikGq-:1858077541) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L68)):*
how about a regex?
```js
const re = /\/(\d+)\/?$/;
const matches = re.match(layerUrl);
if (matches) {
  return parseInt(matches[1]);
}
return null / throw new Error('asdfasf');
```

---

*[src/attribute.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tcIUXV0v7AQUJzYhY:-K8tcIUXV0v7AQUJzYhZ:198831297) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L99)):*
add a FIXME on this so we replace esriRequest once we have something in place that behaves better with proxies

---

*[src/attribute.js, line 179 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8u1Faw2lnDN10fnJqz:-K8u1Faw2lnDN10fnJr-:570990135) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L179)):*
native Promise

---

*[src/attribute.js, line 198 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8uGCgXW8aiyqP_BcZr:-K8uGCgXW8aiyqP_BcZs:-1667387536) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L198)):*
Can this be broken by `oidField = 'id'; attribs = 'nottheidyouarelookingfor,...'` ?

---

*[src/attribute.js, line 247 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8u0I3PZwerOQbF43rt:-K8u0I3PZwerOQbF43ru:-1111525584) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L247)):*
Shorter code:
```js
['skip','attribs'].forEach(o => {
  if (options[layerIdx].hasOwnProperty(o)) { opts[o] = options[layerIdx][o]; }
});
```
Wouldn't mind getting opinions on what people would prefer to read.

---

*[src/attribute.js, line 265 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tziJ3xTwBV7OZHpyy:-K8tziJ3xTwBV7OZHpyz:-436070042) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L265)):*
expand *proper format* -- I guess this is a layer bundle as generated by `newLayerBundle` ?

---

*[src/attribute.js, line 292 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tyrfMz2OeAwMX34wo:-K8tyrfN_7z9CFzXPN0G:442291494) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L292)):*
yes, unless we want to log this / take action it is redundant (same for the .catch below)

---

*[src/attribute.js, line 331 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tyEnIPNU-0gmz7EOH:-K8tyEnJE6cC44syiipo:-1110734966) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L331)):*
I'm having trouble following this.  The comment makes sense, but I don't understand what you are trying to do with idx.  Possibly because I don't understand how layerInfos is structured.

---

*[src/attribute.js, line 374 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tXHTLp-NtqUYkK8sa:-K8tXHTLp-NtqUYkK8sb:219585442) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L374)):*
nitpick: fix capitalization

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-:-K8uGqL9zWutrtbXvpsX:222839130)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/attribute.js, line 16 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tTu8b0RAN3bMHQkNg:-K8uHhlXhMrpepxWtovD:-1407218161) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L16)):*
changed

---

*[src/attribute.js, line 33 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tV36VJ7jbuxs6YUz7:-K8uHy3UWKMY7usGA9jF:894439474) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L33)):*
layerData is populated via a esri service url. That process has no knowledge of the layerId belonging to the layer object, so it cannot assign that value when it builds layerData.  I tack on the layer id during registration so that if code is working with a layerData object, it can easily find the layer object it belongs to.  It's a convenience thing.  I could change it to point to it's parent (the bundle), which also has access to the layerId. 

---

*[src/attribute.js, line 49 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tYE1V-6NY7RWSSln1:-K8uJ3AkzZLHotJPqkkA:-1340711422) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L49)):*
missed one.  fixed.

---

*[src/attribute.js, line 68 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tafqedjD8oHVikGpz:-K8uJb6_7aJeEBFKTVx3:1749885022) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L68)):*
code copied, pasted, corrected

---

*[src/attribute.js, line 179 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8u1Faw2lnDN10fnJqz:-K8uXHTRBnTfoWb1QuHl:684612989) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L179)):*
added fixme for later

---

*[src/attribute.js, line 198 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8uGCgXW8aiyqP_BcZr:-K8uKh_gV_-aWa9kW6NX:1614176381) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L198)):*
Good catch, has been robustified

---

*[src/attribute.js, line 265 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tziJ3xTwBV7OZHpyy:-K8uP0X1Z_E1HEUZ3Sia:1402460342) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L265)):*
what is best way?  ideally it would magically link to [the docs](https://github.com/fgpv-vpgf/geoApi/wiki/Attribute-Loader-Architecture#attribute-data-structure).  I can copy doc details into function header comments, easy enough though comments will be big.  Or can direct in comments to doc pages.  All options are fine with me, would like to know what is preferred. 

---

*[src/attribute.js, line 331 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tyEnIPNU-0gmz7EOH:-K8uV8gu9DF5rVX0B1Ni:723797828) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L331)):*
comments added, let me know if still confusing

---

*[src/attribute.js, line 374 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tXHTLp-NtqUYkK8sa:-K8uUGBbjR2av-CxV9NO:676635175) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L374)):*
Done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/attribute.js, line 68 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tafqedjD8oHVikGpz:-K8uskmoWlSdBbsLZyeG:658206037) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L68)):*
wasn't really a correction, just dealt with a few extra bad URL cases

---

*[src/attribute.js, line 265 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tziJ3xTwBV7OZHpyy:-K8utHeBX9f-4Bumyi8d:1937635198) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L265)):*
some direction is fine, just on the initial reading it's not clear what will be passed if the Promise is resolved (definitely don't copy and paste stuff ... that just means we'll have docs that disagree with each other when one goes out of date)

---

*[src/attribute.js, line 331 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tyEnIPNU-0gmz7EOH:-K8utivLAM-j7A3a68nU:-1219472503) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L331)):*
How it works makes sense.  The question I don't understand is why is idx moved to there (maybe I'm just missing something obvious).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/attribute.js, line 68 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tafqedjD8oHVikGpz:-K8y9WjoK10L8PJ581a6:1953901410) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L68)):*
corrected === sample code had a small bug  :scream: :+1: 

---

*[src/attribute.js, line 265 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tziJ3xTwBV7OZHpyy:-K8yE40gEbOeEcF5Ri0P:-1028443662) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L265)):*
Sounds good, updated comments in next synch.

---

*[src/attribute.js, line 331 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tyEnIPNU-0gmz7EOH:-K8yDQTb0ETmP7hfUuvc:-1970672474) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L331)):*
Service indexes are nested, but the numeric part is flat.  See [this service](http://maps-cartes.ec.gc.ca/ArcGIS/rest/services/E2MS_Atlantic_region_data/MapServer) for example.  If I want to skip index 11, I want to advance my counter to index 16 (thus avoiding all the children of 11). So I find the last child (15), then add 1.  That said, I've discovered a bug for layers that have nesting level > 2, and will apply a fix shortly

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/attribute.js, line 68 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tafqedjD8oHVikGpz:-K8yFzCFO-3WkewdVYsy:1605498549) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L68)):*
:white_check_mark: 

---

*[src/attribute.js, line 331 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8tyEnIPNU-0gmz7EOH:-K8yGGXJDkRpQZwJg463:1625572754) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L331)):*
Suggested comment:
```
// a layer structure like [{ id: 1, subLayerIds: [2, 3], skip: true }, {id: 4}] would be structured as [1, 2, 3, 4]
// in this example once we reach layer 1, we want to skip to 4 and continue
```
The structure isn't exactly right but I think an example would help get the point across.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/attribute.js, line 247 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8u0I3PZwerOQbF43rt:-K92CAukqbFN4wv7BTpO:1881085398) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L247)):*
Would this work?
```js
function pluckOptions(layerIdx, options = {}) {
	return {
		skip: options[layerIdx]['skip'] || false,
		attribs: options[layerIdx]['attribs'] || '*',
	};
}
```

---

*[src/attribute.js, line 331 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K92Emn81fjbO_sy3HtK:-K92Emn81fjbO_sy3HtL:-1749101728) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/072249a10a381d0f3268114888566c9bf37e8e31/src/attribute.js#L331)):*
Is it possible (at all) for a group node to have features stored in it or is it always just a container for child nodes?

---

*[src/attribute.js, line 383 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K92F744hU7V4TCHrwUV:-K92F744hU7V4TCHrwUW:533391066) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/072249a10a381d0f3268114888566c9bf37e8e31/src/attribute.js#L383)):*
Shouldn't this comment block be above the function definition?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/attribute.js, line 247 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K8u0I3PZwerOQbF43rt:-K92M7zfwwnHim_8p2vj:-1258602620) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b1293d2ac1f73194d8884843c85c5e2196eeecba/src/attribute.js#L247)):*
I don't like having to repeat the property names, but it is easier to read than mine.

---

*[src/attribute.js, line 383 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K92F744hU7V4TCHrwUV:-K92Jz7VOiqRPW8NARWo:-1427478265) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/072249a10a381d0f3268114888566c9bf37e8e31/src/attribute.js#L383)):*
No, the outer function returns another function an *attributeLoaderServiceFactory* if you will

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/attribute.js, line 331 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K92Emn81fjbO_sy3HtK:-K92Q-fCbTUUcWVDBSzb:1294578971) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/072249a10a381d0f3268114888566c9bf37e8e31/src/attribute.js#L331)):*
Just a container.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/attribute.js, line 383 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55#-K92F744hU7V4TCHrwUV:-K92R5nUiq8adVyTd9Q6:-990340561) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/072249a10a381d0f3268114888566c9bf37e8e31/src/attribute.js#L383)):*
As long as it's concrete :D

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/55)*

**Pull request merged**
