### PR TITLE
fix(bug): no longer appends url if parameters exist

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1550

## Testing
Tested with own script, did not include since this is a minor change

## Documentation
inline

## Checklist
- [x] `gulp test` succeeds without warnings or errors
- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/179)

### CODE REVIEW

**Comment by alyec** [comment]
Can you change the commit message from `fix(bug)` to `fix(layer)`?  Otherwise :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/179#-:-Kac_8GsqsMsaBlRso0R:bqln0u0)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/179)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/179)*

**Comment by milesap** [comment]
:+1: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/179#-:-KacbUQhwveF4dS6mfK7:b-8fx2u7)*

**Pull request merged**
