### PR TITLE
Handle functiony field names

### PR DESCRIPTION
**Pull request by james-rae**
## Description

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2282

If a functiony field name is found, adds a matching function that returns the field value to chill out the datagrid.

## Testing

Tested against sample file.  Even in IE.

## Checklist

- [ ] `gulp test` succeeds without warnings or errors
- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/252)

### CODE REVIEW

**Comment by barryytm** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/252#-:-Kq9pmpzMQC8xU9DdmKl:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/layer/layerRec/attribRecord.js, line 193 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/252#-KqNLBapiP4RaDBvtYZo:-KqNLBapiP4RaDBvtYZp:b-m1fgik) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/0b8d8ca34ad76217663756cec6b9b287057a2ec5/src/layer/layerRec/attribRecord.js#L193)):*
> ```JavaScript
>         // ignore any functions hanging around on the attribute.
>         return Object.keys(attribs)
>             .filter(key => Object.prototype.toString.call(attribs[key]) !== '[object Function]')
> ```


```js
typeof attribs[key] !== 'function'
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/252)*

**Comment by james-rae** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/layer/layerRec/attribRecord.js, line 193 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/252#-KqNLBapiP4RaDBvtYZo:-KqNyuvQQBwfh4YtmuCh:b1mqxcx) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/0b8d8ca34ad76217663756cec6b9b287057a2ec5/src/layer/layerRec/attribRecord.js#L193)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>


```js
typeof attribs[key] !== 'function'
```
</blockquote></details>

code enhanced. donethanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/252)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/252)*

**Comment by JahidAhmed** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/252)*

**Comment by barryytm** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/252)*

**Pull request merged**
