### PR TITLE
fix(export): correct svg xml so renders on canvas

### PR DESCRIPTION
**Pull request by AleksueiR**
in IE and Firefox

Closes fgpv-vpgf/fgpv-vpgf#1324, fgpv-vpgf/fgpv-vpgf#1307, fgpv-vpgf/fgpv-vpgf#1306

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/167)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Updated release notes: https://github.com/fgpv-vpgf/fgpv-vpgf/releases/tag/untagged-5e3d9f4dccf496492c6c

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/167#-:-KVz5RBMBYFw0oBU6e-0:b3tbmea)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/167#-:-KVz7V_uqauuzqyDudGU:bnfp4nl)*

**Comment by AleksueiR** [comment]
No typos? Yippee!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/167#-:-KVz7hfRYrKzXMpE7Wji:b-hk8rl1)*

**Comment by AleksueiR** [comment]
This might also solve fgpv-vpgf/fgpv-vpgf#1297.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/167#-:-KW-I9BMuA6tTDfWIIQU:bjxcbzb)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/167)*

**Pull request merged**
