### PR TITLE
test(events): add events unit tests

### LINKED ISSUE #28: Create wrapEvents function
* Make a new module in `geoApi` called `events`.  See [the wiki](https://github.com/fgpv-vpgf/geoApi/wiki/How-to-Add-a-New-Section-to-geoApi) for instructions.
* Function name is not set in stone (yet)
* wrapEvents function will be attached to the return object of the `events` module.
* Function will have parameters (names not official yet)
	* esriObject, an ESRI object (at this point, a layer or a map object).
	* handlers, an sub-group of an [event handler definition object](https://github.com/fgpv-vpgf/geoApi/wiki/Event-Handlers#sample-event-handler-object-structure).  Subgroup should match the type of esriObject being passed.  So if a layer is supplied, handlers.layer would be the input.
* Function should wire up any supplied handlers to the corresponding dojo `on` events on the object
    * This allows us to keep Dojo `on` events contained in geoApi
	* Candidate events are on the [wiki](https://github.com/fgpv-vpgf/geoApi/wiki/Event-Handlers#exposed-events)
	* For layers, the `click`, `mouse-over`, and `mouse-out` events only apply to Feature Layers. Utilize function `getLayerType` in `shared.js` to determine layer types.
	* For layers, the `error`, `update-start`, and `update-end` events should add another property to the event parameter called `layer`.  This will point to the value of `target`. It will make the value more intuitive.
* See [RAMP documentation](http://ramp-pcar.github.io/docs/layer-load-en.html) for more info on how ESRI Dojo layer events work
* As time permits, some validation on input objects and handlers could be performed. For example, if a caller passes a map object with layer event handlers, freak out with an error

Sample protoype with no validations, parameter enhancements, or mappings from our event names to dojo event names

```
wrapEvents(esriObject, eventObject) { 
    Object.keys(eventObject).forEach(ourEventName => { 
        esriObject.on(eventMapping[ourEventName], eventObject[ourEventName]); 
    } 
} 

exports = { 
    wrapEvents(esriObject, eventObject) 
}
```

### PR DESCRIPTION
**Pull request by cynngah**
closes #28

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/62)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/62)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[spec/eventSpec.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/62#-K9EAYPmGizk9SirF1i2:-K9EAYPmGizk9SirF1i3:-976059054) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/54967943dd3f41b5fd97610df83bc0c5205c5875/spec/eventSpec.js#L56)):*
good log call :racehorse: :dash: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/62)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/62)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/62)*

**Pull request merged**
