### PR TITLE
Wrap events

### LINKED ISSUE #28: Create wrapEvents function
* Make a new module in `geoApi` called `events`.  See [the wiki](https://github.com/fgpv-vpgf/geoApi/wiki/How-to-Add-a-New-Section-to-geoApi) for instructions.
* Function name is not set in stone (yet)
* wrapEvents function will be attached to the return object of the `events` module.
* Function will have parameters (names not official yet)
	* esriObject, an ESRI object (at this point, a layer or a map object).
	* handlers, an sub-group of an [event handler definition object](https://github.com/fgpv-vpgf/geoApi/wiki/Event-Handlers#sample-event-handler-object-structure).  Subgroup should match the type of esriObject being passed.  So if a layer is supplied, handlers.layer would be the input.
* Function should wire up any supplied handlers to the corresponding dojo `on` events on the object
    * This allows us to keep Dojo `on` events contained in geoApi
	* Candidate events are on the [wiki](https://github.com/fgpv-vpgf/geoApi/wiki/Event-Handlers#exposed-events)
	* For layers, the `click`, `mouse-over`, and `mouse-out` events only apply to Feature Layers. Utilize function `getLayerType` in `shared.js` to determine layer types.
	* For layers, the `error`, `update-start`, and `update-end` events should add another property to the event parameter called `layer`.  This will point to the value of `target`. It will make the value more intuitive.
* See [RAMP documentation](http://ramp-pcar.github.io/docs/layer-load-en.html) for more info on how ESRI Dojo layer events work
* As time permits, some validation on input objects and handlers could be performed. For example, if a caller passes a map object with layer event handlers, freak out with an error

Sample protoype with no validations, parameter enhancements, or mappings from our event names to dojo event names

```
wrapEvents(esriObject, eventObject) { 
    Object.keys(eventObject).forEach(ourEventName => { 
        esriObject.on(eventMapping[ourEventName], eventObject[ourEventName]); 
    } 
} 

exports = { 
    wrapEvents(esriObject, eventObject) 
}
```

### PR DESCRIPTION
**Pull request by cynngah**
Added wrapper module for dojo events.
closes #28 

Unit tests to follow

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/51)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/events.js, line 10 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_rdrfrg5VDkyvUHtF:-K8_rdrfrg5VDkyvUHtG:-470516354) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L10)):*
const

---

*[src/events.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_qqchiUtRecGO0xI2:-K8_qqchiUtRecGO0xI3:-470516354) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L13)):*
const

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/events.js, line 10 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_rdrfrg5VDkyvUHtF:-K8_sNJ10_Yhh-kjOn4d:112004477) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L10)):*
Scratch that-- you don't need toString(); Object.keys() returns an array of strings

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/events.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_xIr9rxmLGx5hSASR:-K8_xIrAmQDDF912bFt3:-1365037961) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L9)):*
For later, we can add some validity checking on the inputs.  For now though, lets keep as is so people can start using events.

---

*[src/events.js, line 22 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_x9Ea7fWda8owEGcQ:-K8_x9Ea7fWda8owEGcR:-1691302972) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L22)):*
can just use `wrapEvents` as it's the same name and there is magic to figure it out

---

*[testEvents.html, line 20 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_x-NlMgsnlrfq2Xd-:-K8_x-NmCgS9TIjB84iW:905692816) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/testEvents.html#L20)):*
:smile_cat: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/events.js, line 16 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8a3rrxi8VFTFHNh7Na:-K8a3rry7MPFrefP81eM:-613239820) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L16)):*
We're missing the extra property mapping (.layer on layer `load`, `update-start`, `update-end`) 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/events.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_xIr9rxmLGx5hSASR:-K8aaymynmcqogZ3Xtbb:-1340295993) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L9)):*
To follow up, let's add the comment now so we don't forget to add the code later.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/events.js, line 20 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8dMYWYk_AOik3oP-r5:-K8dMYWYk_AOik3oP-r6:-682219567) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L20)):*
You can use an arrow function here. () => {}

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Comment by cynngah** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/events.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_xIr9rxmLGx5hSASR:-K8doh7sTxPdfGm-8qAl:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L9)):*
Done.

---

*[src/events.js, line 16 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8a3rrxi8VFTFHNh7Na:-K8f794oJmXDXk0nj7tF:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L16)):*
Done.

---

*[src/events.js, line 20 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8dMYWYk_AOik3oP-r5:-K8doYhYVuITTXWlKgSj:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L20)):*
Done.

---

*[src/events.js, line 22 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_x9Ea7fWda8owEGcQ:-K8doc2Yg4E4wdU4HNJj:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L22)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Comment by alyec** [comment]
general note: all the comments are `feat(core)` when most of them should be `feat(events)`
besides the test page some unit testing should be included I would suggest having one layer and one non-layer event

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-:-K8fKWtMjLLcurPeF2Wu:-2138100454)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/events.js, line 10 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_rdrfrg5VDkyvUHtF:-K8tIXZ87w4WiLJW_ZvO:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L10)):*
Done.

---

*[src/events.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51#-K8_qqchiUtRecGO0xI2:-K8tIXyFY54wBdMRVdXj:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/ab0e99eecbb10fd9e2c59dae95d74b804c5cee49/src/events.js#L13)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/51)*

**Pull request merged**
