### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ec-dev**
use testBasemap.html for demo. Reason: uses ESRI JavaScript API URL instead of Aly's custom built.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/31)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/basemap.js, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31#-K5CekWa-45Yv9TY75B4:-K5CekWa-45Yv9TY75B5:-1934658082) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/95a64bf3846eacd8852e941e8fcd70e3b43f138e/src/basemap.js#L8)):*
Change Ojbect to Object

---

*[src/basemap.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31#-K5CezSqHvUjgczU41-S:-K5CezSqHvUjgczU41-T:-869743588) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/95a64bf3846eacd8852e941e8fcd70e3b43f138e/src/basemap.js#L15)):*
Use let ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/basemap.js, line 23 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31#-K5GKJgNP73jSiqt2tPJ:-K5GKJgNP73jSiqt2tPK:1227343066) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/806401b154dee39d5925e9620b7fe2e47d36123f/src/basemap.js#L23)):*
No need for brackets if an arrow function has only one parameter.

---

*[src/basemap.js, line 27 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31#-K5GKS95_GZT5JFYAM4q:-K5GKS95_GZT5JFYAM4r:166905) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/806401b154dee39d5925e9620b7fe2e47d36123f/src/basemap.js#L27)):*
^

---

*[src/index.js, line 46 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31#-K5GK2EVINweYjAIGqbP:-K5GK2EVINweYjAIGqbQ:-369488862) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/806401b154dee39d5925e9620b7fe2e47d36123f/src/index.js#L46)):*
We are going to build our own basemap switcher ui component. Do we still need to import `BasemapToggle`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/index.js, line 46 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31#-K5GK2EVINweYjAIGqbP:-K5GTCHO9DmtFnaxxFEK:364842159) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/806401b154dee39d5925e9620b7fe2e47d36123f/src/index.js#L46)):*
:+1: , will remove it from the module.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31)*

**Comment by cynngah** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31)*

**Comment by cynngah** [comment]
Reviewed 1 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/31)*

**Pull request merged**
