### PR TITLE
fix(layer): csv file column headings forced unique

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes fgpv-vpgf/fgpv-vpgf#1856

## Testing
eagle eyes

## Documentation
inline

## Checklist

- [x] `gulp test` succeeds without warnings or errors
- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/253)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Are you sure this will work? The updated field names solve binding errors, but won't it break if a modified field is selected to be a lat, long, or primary field?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOXF6p8pTIEVajmssc:b-3ow3d8)*

**Comment by milesap** [comment]
I'm sure it doesn't work (just tested) :smiley:  I'm no expert here but it seems like this solution should work unless I'm missing something. The returned `fields` array contains the updated column names in proper order. Is something ignoring fields and deriving its own column names (the originals)?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOf5oN-Uk-XJXnczxR:b3mlnm2)*

**Comment by barryytm** [comment]
https://github.com/fgpv-vpgf/geoApi/pull/250 was merged in to `v2.1.0`.  It would not cause a problem for now but it would certainly break when we rebase.

**Comment by AleksueiR** [comment]
`validateCSV` provides fields names to the viewer. You are making sure they don't repeat (a,b,b -> a,b_0,b_1), but the actual rows are not touched. If the user selects `b_0` as the primary field, it cannot be matched to the data. That's my understanding anyway. @james-rae, any thoughts?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOhiVCjXmmc6T7N69Y:bwkk55y)*

**Comment by AleksueiR** [comment]
re: @barryytm. This should probably go to `2.1` then, even though it's a bug fix.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOiOUO-XcHj35cypoA:b-y8scnf)*

**Comment by milesap** [comment]
So it _should_ lookup column index by `fields` index but this sounds like something is performing its own search without `fields`. Ok I'll point it to `v2.1.0`

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOik9ceSyDTACYkga8:bif9oea)*

**Comment by james-rae** [comment]
This doesn't work because the validation function is only providing information to the wizard. When the file is actually transformed into a map layer, it's using a library to do that.  That library is not passed these column name overrides; also I don't think it would care if you did.
Two immediate options I see...
1. Reject the file if duplicate names. Make user fix it.
2. In the wizard you have to re-write the file content blob to look as if it always had the new field names.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOirUQZFP0-XVJCZ4o:bwwwwfo)*

**Comment by milesap** [comment]
Option 1 sounds great

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOjiW-97KF5sHUsYap:b-gjs4hm)*

**Comment by james-rae** [comment]
Third option is show warning that duplicate fields will be collapsed.   Let's them load a file without editing it (and accept field loss)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOjmoK-TeY93eeay-B:bjobmwn)*

**Comment by AleksueiR** [comment]
Option 4: provide the wizard with an actual field and a field alias to be used in binding. Re-write wizard to use them.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOjkFWO4H7PPXoQT8y:b-wqzyt)*

**Comment by james-rae** [comment]
This goes beyond binding.  Fields with same names will be collapsed when transforming csv to geoJson

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOkB_shoC4vklCtdD-:b8ighvg)*

**Comment by AleksueiR** [comment]
Option 1 then.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOkN9Db_kOjAMXmr9n:bo24o1o)*

**Comment by milesap** [comment]
:tada: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/253#-:-KqOkPxCT601S3mBUSa-:bjwa7hh)*

**Comment by milesap** [comment]
Will re-open new PR on `v2.1` which rejects CSV files with duplicate columns

**Pull request closed without merging**
