### PR TITLE
WMS GetFeatureInfo and Legend Support

### PR DESCRIPTION
**Pull request by alyec**
Should close https://github.com/fgpv-vpgf/fgpv-vpgf/issues/224 when merged

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/95)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/95)*

**Comment by james-rae** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/95)*

**Comment by ec-dev** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/95)*

**Comment by spencerwahl** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/95)*

**Pull request merged**
