### PR TITLE
Exposing esri graphic stuff

### PR DESCRIPTION
**Pull request by cynngah**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/94)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/proj.js, line 172 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/94#-KE2kOoyFXvEs0ymdefl:-KE2kOozTxXTAmvL3zhk:-1797680636) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4df638ab5f76780a2036fbd05118c0c7a850aa1a/src/proj.js#L172)):*
Capitol G to match the ESRI Class name.  Otherwise everything looks dandy

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/94)*

**Comment by james-rae** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/94)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/94)*

**Comment by cynngah** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/proj.js, line 172 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/94#-KE2kOoyFXvEs0ymdefl:-KE6tiAUobKgBdBmoCR0:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4df638ab5f76780a2036fbd05118c0c7a850aa1a/src/proj.js#L172)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/94)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/94)*

**Pull request merged**
