### PR TITLE
GitHub Templates

### PR DESCRIPTION
**Pull request by alyec**
Add nice templates to geoApi

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/172)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172#-KXMcKEEZARaPOvxsoEg:-KXMcKEEZARaPOvxsoEh:b-hpyzkq) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d91c1e144c25b5d74c0dd000fbc368fcfef536de/.github/PULL_REQUEST_TEMPLATE.md#L17)):*
> ```Markdown
> - [ ] all commit messages are descriptive and follow guidelines
> - [ ] PR targets the correct release version
> - I will assign this PR to the primary reviewer
> ```

[ ] missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172#-KXMcKEEZARaPOvxsoEg:-KXMhsZkgo1U4gWgNx65:b-74hf2w) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d91c1e144c25b5d74c0dd000fbc368fcfef536de/.github/PULL_REQUEST_TEMPLATE.md#L17)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> [ ] missing?
</details>
No, that's intentional since it's something you should go an do as soon as you look at it.  I'm okay with changing it for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172#-KXMcKEEZARaPOvxsoEg:-KXMiDv0dfT3SqmLM2_P:bhvmc1i) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d91c1e144c25b5d74c0dd000fbc368fcfef536de/.github/PULL_REQUEST_TEMPLATE.md#L17)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> No, that's intentional since it's something you should go an do as soon as you look at it.  I'm okay with changing it for consistency.
</details>
I'm good either way. Your call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172#-KXMcKEEZARaPOvxsoEg:-KXMiG_aoZKpkpDwPt6h:b-gw83qw) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d91c1e144c25b5d74c0dd000fbc368fcfef536de/.github/PULL_REQUEST_TEMPLATE.md#L17)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I'm good either way. Your call.
</details>
Then I'm leaving it alone unless someone else expresses a preference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172)*

**Comment by jolevesq** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172#-KXMcKEEZARaPOvxsoEg:-KXMiY8XyJNyQlNYYPmD:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d91c1e144c25b5d74c0dd000fbc368fcfef536de/.github/PULL_REQUEST_TEMPLATE.md#L17)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Then I'm leaving it alone unless someone else expresses a preference.
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/172)*

**Pull request merged**
