### PR TITLE
Symbology

### PR DESCRIPTION
**Pull request by cynngah**
Changed because we're using esri's other renderer format from geoApi now so fetching symbology doesn't break.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/120)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by alyec** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/symbology.js, line 45 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120#-KJa4YKjoNOflYyU0nQb:-KJa4YKjoNOflYyU0nQc:-610970982) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/642b2ea71d5afacf00f31991b5af717a535ca531/src/symbology.js#L45)):*
> ```JavaScript
> 
>     switch (symb.type) {
>         case 'simple':
> ```

Can these strings be moved into constants?  Possibly under shared.js?

---

*[src/symbology.js, line 146 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120#-KJa4QQNicv0RMBe4XYp:-KJa4QQNicv0RMBe4XYq:799635047) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/642b2ea71d5afacf00f31991b5af717a535ca531/src/symbology.js#L146)):*
> ```JavaScript
> 
>         case 'classBreaks':
>             const oidIdx2 = fData.oidIndex[oid];
> ```

What does `oidIdx2` mean?  Can you add a comment or rename the var?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/symbology.js, line 146 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120#-KJa4QQNicv0RMBe4XYp:-KJa5Sq0rFihPUYK7vdd:139163676) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/642b2ea71d5afacf00f31991b5af717a535ca531/src/symbology.js#L146)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> What does `oidIdx2` mean?  Can you add a comment or rename the var?
</details>
it's the same as the oidIdx in the uniqueValues block but it was giving me an error about using 2 consts with the same name for some reason, even though they're in different blocks. I added a 2 instead of renaming it because I thought it would be more straightforward that it's the same variable as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/symbology.js, line 146 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120#-KJa4QQNicv0RMBe4XYp:-KJaBnSE2lrikLGmXxdC:451131504) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/642b2ea71d5afacf00f31991b5af717a535ca531/src/symbology.js#L146)):*
<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> it's the same as the oidIdx in the uniqueValues block but it was giving me an error about using 2 consts with the same name for some reason, even though they're in different blocks. I added a 2 instead of renaming it because I thought it would be more straightforward that it's the same variable as above.
</details>
Pretty sure `case` isn't block scoped.  And at some point we may want to refactor that so we don't have these issues.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 3 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/symbology.js, line 45 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120#-KJa4YKjoNOflYyU0nQb:-KJasIIPdP6rwmpP0qp0:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/642b2ea71d5afacf00f31991b5af717a535ca531/src/symbology.js#L45)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can these strings be moved into constants?  Possibly under shared.js?
</details>
Done.

---

*[src/symbology.js, line 146 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120#-KJa4QQNicv0RMBe4XYp:-KJasJ2TlVH8K17bPQv3:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/642b2ea71d5afacf00f31991b5af717a535ca531/src/symbology.js#L146)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Pretty sure `case` isn't block scoped.  And at some point we may want to refactor that so we don't have these issues.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by james-rae** [comment]
Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by spencerwahl** [comment]
Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Comment by alyec** [comment]
Reviewed 13 of 13 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/120)*

**Pull request merged**
