### PR TITLE
find closest zoom where layer is visible

### PR DESCRIPTION
**Pull request by cynngah**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/107)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/symbology.js, line 616 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/107#-KGqzQhqA5MOoVouEFMr:-KGqzQhrT55MrF_OjYC5:1274534931) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/1877e29babf820cffe776a5991427a64f8a7cd4a/src/symbology.js#L616)):*
Since geoApi should be independent of the viewer the config format should probably be stated explicitly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/107)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/107)*

**Comment by cynngah** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/symbology.js, line 616 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/107#-KGqzQhqA5MOoVouEFMr:-KGr6JvzChXU6g1rnNbV:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/1877e29babf820cffe776a5991427a64f8a7cd4a/src/symbology.js#L616)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/107)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/107)*

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/107)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/107)*

**Pull request merged**
