### PR TITLE
Basic layers module

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/9)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/index.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/9#-K1_QU4PuaEIgsw6xHfA)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/892f54711f11a1547b2eb91dbf41a988f5b8dfbf/src/index.js#L43)):</sup>
question: anonymous function is not supposed to be arrow function?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/9)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/index.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/9#-K1_QU4PuaEIgsw6xHfA)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/892f54711f11a1547b2eb91dbf41a988f5b8dfbf/src/index.js#L43)):</sup>
Since this is the callback to the Dojo require loader I wasn't sure if I should be using arrows (since it changes the meaning of `this`), but I will include a comment.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/9)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/9)

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/9)

**Pull request merged**
