### PR TITLE
Feature/file load

### PR DESCRIPTION
**Pull request by james-rae**
Suite of functions to generate feature layers from files (GeoJson, csv, shapefile)
Projection injection is fairly hack-ish, will entertain alternate ideas.
Unit tests to come later™

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/57)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[package.json, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92xUwRmWijKGQnfEW1:-K92xUwRmWijKGQnfEW2:-752784404) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/package.json#L9)):*
just curious: what is this?

---

*[src/layer.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92xfJha-y-IXfOwYL8:-K92xfJha-y-IXfOwYL9:-1494899348) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L13)):*
Can we put these somewhere else.  I believe we can load json files as `require('defaultRenderers.json')` -- pushing these to a json file might get them away from the rest of the code.

---

*[src/layer.js, line 82 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92y5EyrtwciQuplI5U:-K92y5EyrtwciQuplI5V:-18338767) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L82)):*
would this collide if we have multiple maps on the same page (i.e. is the ESRI layer id supposed to be global per page or just per map)?

---

*[src/layer.js, line 119 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92zGTTnKOhtKDvuODc:-K92zGTTnKOhtKDvuODd:1131107988) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L119)):*
`make____Builder` :+1: 

---

*[src/layer.js, line 142 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K93GunVH6Rhg6OhLoqc:-K93GunVH6Rhg6OhLoqd:1666391874) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L142)):*
most of the variables can be rescoped since we are using let and const instead of var

---

*[src/layer.js, line 330 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K93S_rp7yaTpEc2IP2S:-K93S_rp7yaTpEc2IP2T:475140668) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L330)):*
why not use csvOpts?

---

*[src/layer.js, line 341 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K93Rj9IDiWThRcMuVr8:-K93Rj9IDiWThRcMuVr9:-1425573823) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L341)):*
I think this catch(e) { reject(e) } is redundant as if the Error is not caught it would be thrown for anything handling makeCsvLayer.catch

---

*[src/layer.js, line 366 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K93UIqJScf3gqz-pbfC:-K93UIqJScf3gqz-pbfD:1605498549) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L366)):*
:white_check_mark: 

---

*[testFileLoad.html, line 32 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92z1fqtVSbuyC_PNHB:-K92z1frbgsXwGPNNsBG:171454501) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/testFileLoad.html#L32)):*
bonus points awarded

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[package.json, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92xUwRmWijKGQnfEW1:-K93utbO-Fq-kxbHBvRH:422325591) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/package.json#L9)):*
no clue.  i think it stands for `break rules for success` . but whatever it is, `csv2geojson` freaks out if it's not included.

---

*[src/layer.js, line 82 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92y5EyrtwciQuplI5U:-K93uTBoisaE8Q-O5eB7:727486384) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L82)):*
layer id collision should only be an issue if same ids are inserted into same map.  that said, i was under the impression that geoApi was instantiated once per page (to avoid us re-loading dojo for every map), so IDs should be unique across the page.  do i have a scope / variable lifetime mistake perhaps?

---

*[src/layer.js, line 330 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K93S_rp7yaTpEc2IP2S:-K93u6STCOTFHFYs2Idm:-1854671632) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L330)):*
I can, but will need to transfer the geoJson specific properties that are in `opts` over to `csvOpts`.  which is fine. will do so if you're in agreement.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by alyec** [comment]
for commits: geoApi is not a scope [core, layer or proj]

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/index.js, line 11 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K9407UdzxWf0aLtvKv_:-K9407UdzxWf0aLtvKva:-849143268) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/307cb4fce6a635dd427d3e08c6e72acfaa13e5b1/src/index.js#L11)):*
might want to check if `const x = { somethingUsing(x); }` works, could save some repetition of `api`

---

*[src/layer.js, line 82 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92y5EyrtwciQuplI5U:-K93zRhS8tM_ftp7TNrd:-1694594405) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L82)):*
ESRI is now once per page (via a test on window.require), geoApi is still initialized per map.

---

*[src/layer.js, line 330 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K93S_rp7yaTpEc2IP2S:-K942jEwJHbWxNdiyqf0:965224411) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L330)):*
Nah, I'm fine with leaving it as-is if there's a bunch of extra work to do that way.

---

*[src/layer.js, line 163 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K93zmw_PvNZ7xjBSUIe:-K93zmwa47SS4P0LmBno:-1908859591) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/307cb4fce6a635dd427d3e08c6e72acfaa13e5b1/src/layer.js#L163)):*
these can be hoisted further I think:
```js
const srcLookup = projectionLookup(srcProj,...);
const destLookup = projectionLookup(destProj,...);
const buildLayer = new Promise(resolve => {
  project();
  convert();
  compose = { ... };
  resolve(layer);
});
return srcLookup
  .then(resolve => destLookup)
  .then(resolve => buildLayer);
```
With `projectionLookup` being modified to add the definition once it completes the lookup, or add a couple of intermedidate steps in the promise chain.

---

*[src/layer.js, line 266 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K9424adF0d975I0bcVB:-K9424ae6BJnVxFUBtdt:948484895) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/307cb4fce6a635dd427d3e08c6e72acfaa13e5b1/src/layer.js#L266)):*
with the addition of using `geoApi` for inter-module communication you can reference `makeGeoJsonLayer` from `geoApi`

---

*[src/layer.js, line 297 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K942RhDrD8FFygwv4Za:-K942RhDrD8FFygwv4Zb:1427010344) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/307cb4fce6a635dd427d3e08c6e72acfaa13e5b1/src/layer.js#L297)):*
this try is also redundant

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-:-K945H79WLO-A626dSLe:1508193059)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/layer.js, line 82 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92y5EyrtwciQuplI5U:-K97myrSvoRHZ34i93_5:-1550537155) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L82)):*
It would probably be good to have ids unique across the page (in case we need to support some type of map linking). Is there an "outside-of-angular" space that could manage the id counter, then have the client pass in a seed or a generator function to geoApi?  Alternately, we could always generate a GUID in geoApi.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/layer.js, line 82 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92y5EyrtwciQuplI5U:-K97o2ljSFwVnnO9CKwP:243248221) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L82)):*
We could let the application take care of this, and have it exposed through some sort of registration.  The `FGPV` object in the global scope makes a lot of sense for this, but `geoApi` is not explicitly aware of it.  The app could pass a reference.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by james-rae** [comment]
that's unfortunate, as I quite enjoyed not having to guess which one applied

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index.js, line 11 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K9407UdzxWf0aLtvKv_:-K98TU1U7oehljnnrLe6:-690971627) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/307cb4fce6a635dd427d3e08c6e72acfaa13e5b1/src/index.js#L11)):*
nope.  the param x will have no value.

---

*[src/layer.js, line 82 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K92y5EyrtwciQuplI5U:-K98TgU5fF0y296rhfKh:-858085557) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fec650ad3c46bcd8e3d1f3b9c2f5bfe4ae61b883/src/layer.js#L82)):*
Added option param for caller to supply layerId, and added a "good enough" uuid generator as a fallback.

---

*[src/layer.js, line 266 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K9424adF0d975I0bcVB:-K97r7IpXes2_E31RIfz:248982940) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/307cb4fce6a635dd427d3e08c6e72acfaa13e5b1/src/layer.js#L266)):*
while the circular route to call a function in the same file isn't great, the cleaner code and avoidance of building a function every time you call it clearly makes this the lesser of two evils.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-:-K98SxQOUHe1nrBlcEL7:153654812)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by cynngah** [comment]
Reviewed 3 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/layer.js, line 266 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K9424adF0d975I0bcVB:-K98WNPCsrribe12AKc7:-823186603) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/307cb4fce6a635dd427d3e08c6e72acfaa13e5b1/src/layer.js#L266)):*
Might be worth leaving a comment around in case someone has a better idea.

---

*[src/layer.js, line 86 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K98VHW5gPXkbxaBNdLt:-K98VHW6v8UayZINn-2k:-527364772) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d32aae9fb7131c352fe77ba9a0eeee16db3c7903/src/layer.js#L86)):*
return something at the end to indicate success or failure

---

*[src/layer.js, line 89 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57#-K98VZBxDVCc95lR6l0T:-K98VZBxDVCc95lR6l0U:-827377087) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d32aae9fb7131c352fe77ba9a0eeee16db3c7903/src/layer.js#L89)):*
There is a nicer way to write this `Promise.resolve(null)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/57)*

**Pull request merged**
