### PR TITLE
Legend splitting logic

### PR DESCRIPTION
**Pull request by alyec**
Closes fgpv-vpgf/fgpv-vpgf#1271

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/162)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/legend.js, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162#-KUvnIUWF2qYs8MOwmyj:-KUvnIUY2OCzsnxb8yH-:bs4nu6i) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2462b475822297190b34a2972e3f1e6f99e7e2cc/src/legend.js#L2)):*
> ```JavaScript
> 'use strict';
> const TOO_MANY_LAYERS = 15;
> ```

Need to add `const legend = require('./legend.js');` to `index.js`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162)*

**Comment by AleksueiR** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/legend.js, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162#-KUx-wnhGwn7iJj1DG9M:-KUx-wnhGwn7iJj1DG9N:bfr2cgk) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2462b475822297190b34a2972e3f1e6f99e7e2cc/src/legend.js#L91)):*
> ```JavaScript
>  * @param {int} splitCount the number of pieces which the layer should be broken into
>  * @return a reference to the layer passed in
>  */
> ```

Made modifications - as we discussed - to the split function to account for item gutter space in the legend. See this awesome, complimentary diagram about whitespace: https://i.imgur.com/72ZnvIn.png :smile: 

```js
function splitLayer(layer, initialSplitCount) {
    if (initialSplitCount === 1) {
        return layer;
    }
    
    // get initial chunk suze for starters
    let initalChunkSize = layer.height / initialSplitCount;
    
    // get initial splits and whitespace with initial chunk size; this will serve to determine the steps at which the chunk size will be increased
    let { splits: minSplits, whiteSpace: minWhiteSpace } = findSplits(initalChunkSize, initialSplitCount);
    
    const stepCount = 8; // number of attempts
    const step = minWhiteSpace / stepCount;

    // calculate splits while increasing the chunk size
    for (let i = 1; i <= stepCount; i++) {
        initalChunkSize += step;
        
        let { splits, whiteSpace } = findSplits(initalChunkSize, initialSplitCount);
      
      // store splits corresponding to the minimum whitespace
      if (whiteSpace < minWhiteSpace) {
            minWhiteSpace = whiteSpace;
            minSplits = splits;
        }
    }
  
    //console.log(minSplits)
    // apply split to the splits that result in the minimum of whitespace
    minSplits.forEach(split =>
        split.wrap = true);

    //console.log(minWhiteSpace)
    
    function findSplits(chunkSize, splitCount) {
 
        let itemYOffset = layer.y;
        let itemYMax = 0;
        const splits = [];
        let whiteSpace = 0;

        function traverse(items) {
            items.forEach(item => {
                
                if (splitCount === 1) {
                    return;
                }
                
                // this is the y coordinate of the item's bottom boundary
                itemYMax = item.y + (item.type === 'group' ? item.headerHeight : item.height);
            
                if (itemYMax - itemYOffset >= chunkSize) {
                    splitCount --;
                    
                    // whitespace is created when an item sitting on the boundary pulled into the next chunk, the space it would have occupied is wasted; the waste doubles as the entire item is moved to the next legend chunk
                    whiteSpace += (chunkSize - (item.y - itemYOffset)) * 2;
                    itemYOffset += chunkSize;
                    splits.push(item);
                }         
            
            
                if (item.type === 'group') {
                    traverse(item.items);
                }
            });
        }

        traverse(layer.items);

        return {
            whiteSpace,
            splits
        };
    }

    return layer;
}
```

Split example: https://i.imgur.com/RO9lcGH.png

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162)*

**Comment by alyec** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/legend.js, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162#-KUvnIUWF2qYs8MOwmyj:-KVAp7Jnb1fKvBqY-Afb:bb7f2mf) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2462b475822297190b34a2972e3f1e6f99e7e2cc/src/legend.js#L2)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Need to add `const legend = require('./legend.js');` to `index.js`.
</details>
done

---

*[src/legend.js, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162#-KUx-wnhGwn7iJj1DG9M:-KVApCU_ZbmHykbLGLFG:bb7f2mf) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2462b475822297190b34a2972e3f1e6f99e7e2cc/src/legend.js#L91)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Made modifications - as we discussed - to the split function to account for item gutter space in the legend. See this awesome, complimentary diagram about whitespace: https://i.imgur.com/72ZnvIn.png :smile: 
> 
> ```js
> function splitLayer(layer, initialSplitCount) {
>     if (initialSplitCount === 1) {
>         return layer;
>     }
>     
>     // get initial chunk suze for starters
>     let initalChunkSize = layer.height / initialSplitCount;
>     
>     // get initial splits and whitespace with initial chunk size; this will serve to determine the steps at which the chunk size will be increased
>     let { splits: minSplits, whiteSpace: minWhiteSpace } = findSplits(initalChunkSize, initialSplitCount);
>     
>     const stepCount = 8; // number of attempts
>     const step = minWhiteSpace / stepCount;
> 
>     // calculate splits while increasing the chunk size
>     for (let i = 1; i <= stepCount; i++) {
>         initalChunkSize += step;
>         
>         let { splits, whiteSpace } = findSplits(initalChunkSize, initialSplitCount);
>       
>       // store splits corresponding to the minimum whitespace
>       if (whiteSpace < minWhiteSpace) {
>             minWhiteSpace = whiteSpace;
>             minSplits = splits;
>         }
>     }
>   
>     //console.log(minSplits)
>     // apply split to the splits that result in the minimum of whitespace
>     minSplits.forEach(split =>
>         split.wrap = true);
> 
>     //console.log(minWhiteSpace)
>     
>     function findSplits(chunkSize, splitCount) {
>  
>         let itemYOffset = layer.y;
>         let itemYMax = 0;
>         const splits = [];
>         let whiteSpace = 0;
> 
>         function traverse(items) {
>             items.forEach(item => {
>                 
>                 if (splitCount === 1) {
>                     return;
>                 }
>                 
>                 // this is the y coordinate of the item's bottom boundary
>                 itemYMax = item.y + (item.type === 'group' ? item.headerHeight : item.height);
>             
>                 if (itemYMax - itemYOffset >= chunkSize) {
>                     splitCount --;
>                     
>                     // whitespace is created when an item sitting on the boundary pulled into the next chunk, the space it would have occupied is wasted; the waste doubles as the entire item is moved to the next legend chunk
>                     whiteSpace += (chunkSize - (item.y - itemYOffset)) * 2;
>                     itemYOffset += chunkSize;
>                     splits.push(item);
>                 }         
>             
>             
>                 if (item.type === 'group') {
>                     traverse(item.items);
>                 }
>             });
>         }
> 
>         traverse(layer.items);
> 
>         return {
>             whiteSpace,
>             splits
>         };
>     }
> 
>     return layer;
> }
> ```
> 
> Split example: https://i.imgur.com/RO9lcGH.png
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162)*

**Comment by AleksueiR** [comment]
:lgtm: Awesome!

---

Reviewed 2 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162#-:-KVBR-y7k-NFUxW688On:bswp6el)*

**Comment by AleksueiR** [comment]
Codepen with demo here: codepen.io/AleksueiR/pen/EgXLKm

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162#-:-KVBRW4xDk18xBWyxhpg:b96fm8n)*

**Comment by james-rae** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/162)*

**Pull request merged**
