### PR TITLE
Encode SVG to base64

### PR DESCRIPTION
**Pull request by james-rae**
since IE will process in-string html tags as real tags, change SVG strings to be encoded

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/137)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/137)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/137#-:-KN8KBmpcV7D4lnWaBQ7:1417088721)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/137)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/137)*

**Pull request merged**
