### PR TITLE
fix(build): correct dependency tree for webpack

### PR DESCRIPTION
**Pull request by milesap**
These changes allow geoapi to be consumed by an external webpack build
system.

All dependency versions moved to latest.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/217)

### CODE REVIEW

**Comment by milesap** [comment]
Correct, it removes geoApi building within geoApi itself. Testing continues with `npm run test` locally using jasmine. Page tests would not work currently. 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/217#-:-KlTqnHl0DUrV_YbU-u2:bafay7b)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 6 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/217#-KlTjKRg4Ei7k0511c8X:-KlTt6l3CHbXOOAh39RZ:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e5bca3055303b669feb6c75b67576c279efaec76/.travis.yml#L6)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Might as well remove `gulp.config.js`.
</blockquote></details>

:+1: 

---

*[package.json, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/217#-KlTj5SpnwgHX7hEXqHC:-KlTssyPvDKHxH25Mzdk:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/8f8dbd06023230b58d8b312ad8ec9b0c3ab1fbfc/package.json#L2)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I don't think renaming the package is a good idea at this point.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/217)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/217)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/217#-:-KlYxwD3NLyVU4FvSTCb:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 5 of 6 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/217)*

**Pull request merged**
