### PR TITLE
feat(export): return local and server based images as separate promises

### PR DESCRIPTION
**Pull request by AleksueiR**
also, render an image for __all__ vector layers locally on the client since it's faster

Relates fgpv-vpgf/fgpv-vpgf#1267

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/161)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/mapPrint.js, line 143 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KU3Jhy9WnJQ_80J4buP:-KU3Jhy9WnJQ_80J4buQ:bi98k5h) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/658cb6864982d42caf0882324eea8df84527e10a/src/mapPrint.js#L143)):*
> ```JavaScript
> *
> * @param {String} url image url to convert (result from the esri print task)
> * @return {Promise} convertion promise resolving into a canvas of the image
> ```

typo: conversion

---

*[src/mapPrint.js, line 131 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUFSLW3bzAwx91oWvDo:-KUFSLW49Sze6lVSybXI:bwayyhy) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb0866c5108ac5a3f44b023348553248d8fc2d00/src/mapPrint.js#L131)):*
> ```JavaScript
>         canvg(localCanvas, svgtext, {
>             renderCallback: () =>
>                 resolve(localCanvas)
> ```

Does `canvg` have an error event we can use for rejecting the promise?

---

*[src/mapPrint.js, line 174 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUFSnBwG4whjeIIgJ0x:-KUFSnBwG4whjeIIgJ0y:b28yuzl) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb0866c5108ac5a3f44b023348553248d8fc2d00/src/mapPrint.js#L174)):*
> ```JavaScript
> * @param {Object} esriBundle bundle of API classes
> * @param {Object} geoApi geoApi to determine if we are in debug mode
> * @return {Object} with two promises - local and server canvas; each promise resolves with a corresponding canvas
> ```

Can you add a note about how errors are returned / handled?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161)*

**Comment by AleksueiR** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/mapPrint.js, line 143 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KU3Jhy9WnJQ_80J4buP:-KUHNOhDfsH4F76xasVZ:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/658cb6864982d42caf0882324eea8df84527e10a/src/mapPrint.js#L143)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: conversion
</details>
Done.

---

*[src/mapPrint.js, line 131 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUFSLW3bzAwx91oWvDo:-KUHMiG07LdkWXNsmKWm:bmuo20q) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb0866c5108ac5a3f44b023348553248d8fc2d00/src/mapPrint.js#L131)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Does `canvg` have an error event we can use for rejecting the promise?
</details>
It doesn't seem to have one. Would wrapping `canvg` in a `try/catch` work?

---

*[src/mapPrint.js, line 174 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUFSnBwG4whjeIIgJ0x:-KUHO94F4gnc4BgecSim:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb0866c5108ac5a3f44b023348553248d8fc2d00/src/mapPrint.js#L174)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you add a note about how errors are returned / handled?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/mapPrint.js, line 131 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUFSLW3bzAwx91oWvDo:-KUHhKcF0DkFiYWE_inj:b5kglwi) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb0866c5108ac5a3f44b023348553248d8fc2d00/src/mapPrint.js#L131)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> It doesn't seem to have one. Would wrapping `canvg` in a `try/catch` work?
</details>
It will probably only catch errors raised during the constructor call, but that may still be worthwhile.

---

*[src/mapPrint.js, line 14 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUHpIQVmsm71I6oFyYy:-KUHpIQWrLY79xAhV0Ac:b-dg57qt) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb576c5c525bf31bcd787613c1f21e04ec224bd2/src/mapPrint.js#L14)):*
> ```JavaScript
>   * This module exports an object with the following functions
>   * - `printMap`
>   */
> ```

Can you include a general note on why unit tests will not work for this module very well (DOM required)?

---

*[src/mapPrint.js, line 130 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUHp05QRhY10HlVHsHr:-KUHp05QRhY10HlVHsHs:bfwbgh) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb576c5c525bf31bcd787613c1f21e04ec224bd2/src/mapPrint.js#L130)):*
> ```JavaScript
>         // convert svg text to canvas and stuff it into localCanvas canvas dom node
>         canvg(localCanvas, svgtext, {
>             useCORS: true,
> ```

Since IE11 has mixed reports on crossorigin images we should test this out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161)*

**Comment by AleksueiR** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/mapPrint.js, line 131 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUFSLW3bzAwx91oWvDo:-KUNRqDntBfnC6KtJIC0:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb0866c5108ac5a3f44b023348553248d8fc2d00/src/mapPrint.js#L131)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> It will probably only catch errors raised during the constructor call, but that may still be worthwhile.
</details>
Done.

---

*[src/mapPrint.js, line 14 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUHpIQVmsm71I6oFyYy:-KUNQc_U5R3rzOplnZdQ:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb576c5c525bf31bcd787613c1f21e04ec224bd2/src/mapPrint.js#L14)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you include a general note on why unit tests will not work for this module very well (DOM required)?
</details>
Done.

---

*[src/mapPrint.js, line 130 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUHp05QRhY10HlVHsHr:-KUNR79IsFN8vxqYBxQv:b-1hl0xp) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb576c5c525bf31bcd787613c1f21e04ec224bd2/src/mapPrint.js#L130)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Since IE11 has mixed reports on crossorigin images we should test this out.
</details>
Can we do it as a separate PR? There is already an issue to fix legend appearance for IE, maybe we can lump it together with this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mapPrint.js, line 130 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-KUHp05QRhY10HlVHsHr:-KUNTV6K0QUZm_6K8z-O:b5ft58r) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bb576c5c525bf31bcd787613c1f21e04ec224bd2/src/mapPrint.js#L130)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Can we do it as a separate PR? There is already an issue to fix legend appearance for IE, maybe we can lump it together with this one.
</details>
:white_check_mark:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161#-:-KUNTs2QkjECZ8yy53pk:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/161)*

**Pull request merged**
