### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ec-dev**
add scalebar module, add scalebar setup in mapManager, add scalebar demo page.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/36)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/36#-K5l92YC-VvcmbKkY0YS:-K5l92YDrG0i23deDP_S:713808270) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/1343fc12b958a0bd4535194978a7cf254e21157b/src/index.js#L56)):*
Can we keep the dojo dependancies in alphabetical order?

---

*[src/scalebar.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/36#-K5l9SnWtTqbaPL0QOdu:-K5l9SnWtTqbaPL0QOdv:815021012) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/1343fc12b958a0bd4535194978a7cf254e21157b/src/scalebar.js#L1)):*
If this is all this file does, maybe just include esriBundle.Scalebar as part of MapManager's return object?  Or is there plans for more stuff in this file?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/36)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/scalebar.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/36#-K5l9SnWtTqbaPL0QOdu:-K5l9qlxmh0sBoOvVo_b:-500125199) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/1343fc12b958a0bd4535194978a7cf254e21157b/src/scalebar.js#L1)):*
That's it, I looked up on RAMP for other things, but nothing. I will make it part of MapManager.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/36)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/36)*

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/36)*

**Comment by cynngah** [comment]
Reviewed 1 of 4 files at r1, 2 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/36)*

**Pull request merged**
