### PR TITLE
Symbology

### PR DESCRIPTION
**Pull request by cynngah**
Relates to #616 in fgpv

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/123)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/proj.js, line 118 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123#-KJuoxH1ARZwAaOSdYFH:-KJuoxH2hnaxzLfGPq26:-94067721) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/692c549a48bb0ab79ac9d09e290e8a1e158ef340/src/proj.js#L118)):*
> ```JavaScript
> }
> 
> function checkProj(spatialReference) {
> ```

Needs jsdoc and unit tests should be pretty easy to write for this one.

In the function you are throwing an error which is immediately caught.  If you want to return a meaningful error you might want to return an object like `{foundProj: false, message:'Source projection not recognized'}` instead of a boolean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123)*

**Comment by james-rae** [comment]
*[src/proj.js, line 118 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123#-KJuoxH1ARZwAaOSdYFH:-KJuqO9hc-gnCxaht_J0:340528265) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/692c549a48bb0ab79ac9d09e290e8a1e158ef340/src/proj.js#L118)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Needs jsdoc and unit tests should be pretty easy to write for this one.
> 
> In the function you are throwing an error which is immediately caught.  If you want to return a meaningful error you might want to return an object like `{foundProj: false, message:'Source projection not recognized'}` instead of a boolean.
</details>
Or alternately, remove the error throws all together and just just return false in those spots.  I'm fine with this or aly's approach

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/proj.js, line 118 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123#-KJuoxH1ARZwAaOSdYFH:-KJusAqwTRsR2iLE_ZCr:424770732) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/692c549a48bb0ab79ac9d09e290e8a1e158ef340/src/proj.js#L118)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> Or alternately, remove the error throws all together and just just return false in those spots.  I'm fine with this or aly's approach
</details>
Sorry, I did mean remove the throws and add meaningful messages by having a structured return type.  If we don't care why we can't project I'm fine with keeping a simple boolean return type as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123)*

**Comment by cynngah** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/proj.js, line 118 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123#-KJuoxH1ARZwAaOSdYFH:-KJuzSsU-8qZ3dFOaX1P:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/692c549a48bb0ab79ac9d09e290e8a1e158ef340/src/proj.js#L118)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Sorry, I did mean remove the throws and add meaningful messages by having a structured return type.  If we don't care why we can't project I'm fine with keeping a simple boolean return type as well.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/123)*

**Pull request merged**
