### PR TITLE
feat(layer): server side identify

### PR DESCRIPTION
**Pull request by james-rae**
Identify function for Dynamic Layers

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/66)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/layer.js, line 44 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/66#-K9YeydfMVREU45yxT_E:-K9YeydfMVREU45yxT_F:1090272659) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/dd0c5462ba5927fe58dc132567983553aaf19958/src/layer.js#L44)):*
Is this empty array if no hits are found?  If so can we add it to the return comment?

---

*[src/layer.js, line 58 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/66#-K9Ye_Bb9NgWrWz9zqpb:-K9Ye_Bb9NgWrWz9zqpc:315463015) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/dd0c5462ba5927fe58dc132567983553aaf19958/src/layer.js#L58)):*
Using the fancy ES6 string replacement.  Looks like we have another ES6 convert.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/66)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/66)*

**Comment by ec-dev** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/66)*

**Comment by james-rae** [comment]
*[src/layer.js, line 58 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/66#-K9Ye_Bb9NgWrWz9zqpb:-K9Yj1slhR2plilOMZ5u:-650090966) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/dd0c5462ba5927fe58dc132567983553aaf19958/src/layer.js#L58)):*
Took me 20 minutes to realize I needed angled single quotes :pig2: :dash: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/66)*

**Pull request merged**
