### PR TITLE
feat(geo): expose layer drawing options

### PR DESCRIPTION
**Pull request by AleksueiR**
Relates fgpv-vpgf/fgpv-vpgf#434

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/96)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96)*

**Comment by james-rae** [comment]
*[src/index.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96#-KFB3cpAbKjaSpb7pHyb:-KFB3cpAbKjaSpb7pHyc:-1947195164) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/8fffe3e6a2e400eb00e9229c46de0a49aa14e9c6/src/index.js#L56)):*
alphabetical order fail :hamburger: :hammer: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/index.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96#-KFB3cpAbKjaSpb7pHyb:-KFB4-JXhm4zWkjNoMeU:1661533079) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/8fffe3e6a2e400eb00e9229c46de0a49aa14e9c6/src/index.js#L56)):*
Need to add this to the [guide](https://github.com/fgpv-vpgf/geoApi/wiki/How-to-Add-an-ESRI-API-Class).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96)*

**Comment by james-rae** [comment]
*[src/index.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96#-KFB3cpAbKjaSpb7pHyb:-KFB4XAUwlclRWvt-g0h:-472701157) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/8fffe3e6a2e400eb00e9229c46de0a49aa14e9c6/src/index.js#L56)):*
added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96)*

**Comment by AleksueiR** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/index.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96#-KFB3cpAbKjaSpb7pHyb:-KFEMymHBhgmycdITaX4:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/8fffe3e6a2e400eb00e9229c46de0a49aa14e9c6/src/index.js#L56)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96)*

**Comment by ec-dev** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96)*

**Comment by ec-dev** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/96)*

**Pull request merged**
