### PR TITLE
feat(layer): expose ESRI query

### PR DESCRIPTION
**Pull request by james-rae**
Just exposing a class needed to handle feature layer drill-through identify

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/77)

### CODE REVIEW

**Comment by alyec** [comment]
I think this needs some pretty extensive unit testing.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/77#-:-KALEZ19ZhzyHoiNDydc:1259354512)*

**Comment by james-rae** [comment]
my unit test was `gulp check` :pig2: :dash: 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/77#-:-KALEpTDm5eSDY-ckc--:143009424)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/77)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/77)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/77)*

**Pull request merged**
