### PR TITLE
fix(symbol): svg size is too big when undefined

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Solve a problem added from my PR review
Close #1600

## Testing

Chrome, FF and Safari

## Checklist

- [x] `gulp test` succeeds without warnings or errors
- [ ] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/182)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182#-KdSCN7uLrLdrx1rjMU8:-KdSCN7uLrLdrx1rjMU9:boejux0) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/a40c352c6ef346d812e1e7ea0d65f0e55bdbe549/package.json#L3)):*
> ```JSON
> {
>   "name": "geoApi",
>   "version": "1.1.2-1",
> ```

`1.1.3-1` (the `-1` means prerelease)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182#-:-KdW38-n7LWWFd6Xrr6M:bnfp4nl)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182#-KdSCN7uLrLdrx1rjMU8:-KdW3Up4YIwna4Kfbmby:bn0pvfr) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/a40c352c6ef346d812e1e7ea0d65f0e55bdbe549/package.json#L3)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

`1.1.3-1` (the `-1` means prerelease)
</blockquote></details>

I should only put 1.1.3 then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182#-KdSCN7uLrLdrx1rjMU8:-KdWGJL3shScLQSn_Zq7:b-2j5k57) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/a40c352c6ef346d812e1e7ea0d65f0e55bdbe549/package.json#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I should only put 1.1.3 then?
</blockquote></details>

Sure 1.1.3 works (means no update required when we finally release)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182)*

**Comment by jolevesq** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182#-KdSCN7uLrLdrx1rjMU8:-KdWObyJKRgjEB--t-pM:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/a40c352c6ef346d812e1e7ea0d65f0e55bdbe549/package.json#L3)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Sure 1.1.3 works (means no update required when we finally release)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/symbology.js, line 166 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182#-KdWUDzBocBRTT6Wo5s6:-KdWUDzBocBRTT6Wo5s7:bye7xrf) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/6eab4398040eb0f99b5cbf2f3328e96907dd00e4/src/symbology.js#L166)):*
> ```JavaScript
>     // make an empty svg graphic in case nothing is found to avoid undefined inside the filters
>     if (typeof svgcode === 'undefined') {
>         svgcode = svgjs(document.createElement('div')).size(32, 32).svg();
> ```

Actually, instead of hardcoding 32, you can use the `CONTAINER_SIZE` constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182)*

**Comment by jolevesq** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/symbology.js, line 166 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182#-KdWUDzBocBRTT6Wo5s6:-KdWwIbCVq_x3OEIinKh:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/6eab4398040eb0f99b5cbf2f3328e96907dd00e4/src/symbology.js#L166)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Actually, instead of hardcoding 32, you can use the `CONTAINER_SIZE` constant.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/182)*

**Pull request merged**
