### PR TITLE
Legend Section Allocation Fix

### PR DESCRIPTION
**Pull request by alyec**
Closes fgpv-vpgf/fgpv-vpgf#1370

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/169)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/legend.js, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/169#-KXM0SdcTouNere8KF_T:-KXM0SddIKq-xsXc1VBs:b-ada39w) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/5a5628650ecc929e976b6cff443939bfab514a38/src/legend.js#L55)):*
> ```JavaScript
>  * @param {Array} layers a list of layers to be updated (modified in place)
>  * @param {int} sections the number of sections to use
>  * @return an object in the form { layers, sectionsUsed, bestPerm, bestHeight }
> ```

Make sure these braces dont break the doc build

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/169)*

**Comment by alyec** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/legend.js, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/169#-KXM0SdcTouNere8KF_T:-KXMAVdKlbCcFGZAcTyA:bb7f2mf) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/5a5628650ecc929e976b6cff443939bfab514a38/src/legend.js#L55)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> Make sure these braces dont break the doc build
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/169)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/169)*

**Comment by milesap** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/169)*

**Pull request merged**
