### PR TITLE
feat(ui): changes to help symbology expand large images

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1298

## Testing

:eyes: 

## Checklist

- [ ] `gulp test` succeeds without warnings or errors
- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas, @barryytm, @ShrutiVellanki, and @JahidAhmed)

---

*[src/symbology.js, line 393 at r1](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307#-LG0b2xoDOchRvaMi0VP:-LG0b2xoDOchRvaMi0VQ:b-rgqvt7) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/f93a80be873142e6e1f777747187c1c6bb60d14a/src/symbology.js#L393)):*
> ```JavaScript
>  * @param {Function} conversionFunction a conversion function to wrap the supplied image into an image or an icon style symbology container
>  * @param {Array} list a list of config-supplied symbology items in the form of [ { text: <String>, image: <String> }, ... ] wher `image` can be dataURL or an actual url
>  * @return {Array} an array of converted symbology symbols in the form of [ { name: <String>, svgcode: <String> }, ... ]; items will be populated async as conversions are done
> ```

add new property to return value donethanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307)*

**Comment by barryytm** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas, @ShrutiVellanki, and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307)*

**Comment by ShrutiVellanki** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307)*

**Comment by dane-thomas** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[src/symbology.js, line 393 at r1](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307#-LG0b2xoDOchRvaMi0VP:-LG0cVuGAROeHmhofkLG:bcze0ta) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/f93a80be873142e6e1f777747187c1c6bb60d14a/src/symbology.js#L393)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

add new property to return value donethanks!
</blockquote></details>

donethanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307)*

**Pull request merged**
