### PR TITLE
Increase size of legend symbols

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2420

Take the the original size and multipy it by 1.33333 then round it to an integer 
## Testing

Use tag `v2.1.0-16`
Try http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0
## Documentation

NA
## Checklist

- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/270)

### CODE REVIEW

**Comment by james-rae** [comment]
Can you publish a version of geoApi so people can test this? I think next is `v2.1.0-16`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270#-:-Kwg06mT3pkDbtbru4XH:b5t3vt9)*

**Comment by barryytm** [comment]
Tag `v2.1.0-16` which contains this PR has been pushed.  Feel free to test with it

**Comment by james-rae** [comment]
Pretty elegant solution. I'm unable to break it. 

Maybe just add a comment above the `switch` block explaining that we are converting points to pixels using 1.3333 as factor.

Also, need to check existence of and apply your fix to any `defaultSymbol` in the the two non-simple renderers. See [renderer spec](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Renderer_objects/02r30000019t000000/)

I also notice the graphic on a hovertip is smaller, but this seems to apply to image-based symbols too, so might be CSS of the hovertip. Alex can verify if the behavior is correct.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270#-:-Kwg5Xd37kfciCQDHr8I:b-68yqx4)*

**Comment by AleksueiR** [comment]
@james-rae You are correct - images in the tooltips are scaled to fit inside the tooltip, which has a fixed height, so it's normal for them to smaller.

With some layers, symbols larger than their container boxes will appear the same size, as in Ozone layer. This is also normal.

| current  |  this PR |
|---|---|
|   |   |

:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/symbology.js, line 828 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270#-KwjFpw1WffbDCMkmr8k:-KwjFpw1WffbDCMkmr8l:b-n5fyjm) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/504bd9d277e5cd9dfb1e687e61a9caeff32a0f5e/src/symbology.js#L828)):*
> ```JavaScript
>         switch (renderer.type) {
>             case SIMPLE:
>                 renderer.symbol.size = Math.round(renderer.symbol.size * 1.33333);  // increase the size of the symbol
> ```

Can you pull 1.33 into a variable? Otherwise it's just a magic number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270#-:-KwjGcyT_7UQyAGgcSsE:b-oq5pfv)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270)*

**Comment by james-rae** [comment]
*[src/symbology.js, line 838 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270#-KwolHUWKQsEVb7SWpFt:-KwolHUWKQsEVb7SWpFu:bbux27m) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/f1f6f14d1c4a7b3b99b9b29d6f047ce4be9318b6/src/symbology.js#L838)):*
> ```JavaScript
>             case UNIQUE_VALUE:
>                 if (renderer.defaultSymbol) {
>                     renderer.defaultSymbol.size = Math.round(renderer.defaultSymbol * ptFactor);
> ```

should be `renderer.defaultSymbol.size = Math.round(renderer.defaultSymbol.size * ptFactor);`, same in the line below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270)*

**Comment by barryytm** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/symbology.js, line 828 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270#-KwjFpw1WffbDCMkmr8k:-KwonUi_ZM2hf40Lovjt:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/0006fb2a3e993907f3ff6942d6432565f317509e/src/symbology.js#L828)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you pull 1.33 into a variable? Otherwise it's just a magic number.
</blockquote></details>

done, thanks

---

*[src/symbology.js, line 838 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270#-KwolHUWKQsEVb7SWpFt:-KwonR6HDENMpxdXCrRC:b-z9vwkf) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/f1f6f14d1c4a7b3b99b9b29d6f047ce4be9318b6/src/symbology.js#L838)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

should be `renderer.defaultSymbol.size = Math.round(renderer.defaultSymbol.size * ptFactor);`, same in the line below.
</blockquote></details>

corrected, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/270)*

**Pull request merged**
