### PR TITLE
refactor(geoApi): create common function module

### PR DESCRIPTION
**Pull request by james-rae**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/39)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/39)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/shared.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/39#-K7LrU1Z4cpDKuNo3TSt:-K7LrU1Z4cpDKuNo3TSu:-2032218246) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/f00ac195f1e29b4f794db91720186a200cb8d9c6/src/shared.js#L4)):*
Maybe use the arrow function.

---

*[src/shared.js, line 28 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/39#-K7LrbBP7YvP39oCwucu:-K7LrbBP7YvP39oCwucv:1397389228) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/f00ac195f1e29b4f794db91720186a200cb8d9c6/src/shared.js#L28)):*
You can use the object shortcut here. @alyec mentioned it in the last PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/146#issuecomment-168051133

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/39)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/39)*

**Comment by AleksueiR** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/39#-:-K7MLXSD3SaXzYlOA2Mh:980077423)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/39)*

**Pull request merged**
