### PR TITLE
feat(print): Create Map Image from Print Service and user added layer

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1157, #1160

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/156)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/mapPrint.js, line 26 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KToomjs8I8_vSudSb94:-KToomjs8I8_vSudSb95:b-bvevak) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/3faddd1fc0c9bed44f6dcb0acd1606eee09cf44e/src/mapPrint.js#L26)):*
> ```JavaScript
> *                           url - for the esri geometry server
> *                           format - output format
> * @return {Promise} resolving when the print task created the image
> ```

can you add a note about what value will be contained in the promise?

---

*[src/mapPrint.js, line 118 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KTosDCouDd3xEn_Foiz:-KTosDCouDd3xEn_Foj-:b4k1lqz) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/3faddd1fc0c9bed44f6dcb0acd1606eee09cf44e/src/mapPrint.js#L118)):*
> ```JavaScript
> *
> * @param {Object} map esri map object
> * @return {Promise} resolving when the canvas have been created
> ```

Can you add a note that this resolves with the image element?

---

*[src/mapPrint.js, line 174 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KTorAUPYaxdz0FpkNV4:-KTorAUPYaxdz0FpkNV5:bvikd2d) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/3faddd1fc0c9bed44f6dcb0acd1606eee09cf44e/src/mapPrint.js#L174)):*
> ```JavaScript
> * @param {Object} esriBundle bundle of API classes
> * @param {Object} geoApi geoApi to determine if we are in debug mode
> * @return {Object} canvas the complete boolean value and the new canvas element if true or the error
> ```

Can you split the return line the same way you used for `options` above?  Something like:
```text
@return {Object} the result and status of the print call
                        - complete [bool]: true if the call was successful, false otherwise
                        - canvas [HTMLCanvasElement]: the canvas of the composite image (only set if complete is true)
                        - error[?]: the error details / exception object (only set if complete is false)
```

---

*[src/mapPrint.js, line 206 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KToqWkgq1UYSqhmJQmE:-KToqWkgq1UYSqhmJQmF:b-bjt78g) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/3faddd1fc0c9bed44f6dcb0acd1606eee09cf44e/src/mapPrint.js#L206)):*
> ```JavaScript
> 
>                     // return canvas
>                     resolve({ complete: true, canvas: canvas });
> ```

small style fix here and below `canvas: canvas` can be changed to `canvas` (it will automatically name the property with the same name in ES6)
applies to `error: error` as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156)*

**Comment by jolevesq** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/mapPrint.js, line 26 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KToomjs8I8_vSudSb94:-KTpW_HFm-PVHiXHc4B4:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/3faddd1fc0c9bed44f6dcb0acd1606eee09cf44e/src/mapPrint.js#L26)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> can you add a note about what value will be contained in the promise?
</details>
Done.

---

*[src/mapPrint.js, line 118 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KTosDCouDd3xEn_Foiz:-KTpW_y-fpMKV8ubGdmB:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/3faddd1fc0c9bed44f6dcb0acd1606eee09cf44e/src/mapPrint.js#L118)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you add a note that this resolves with the image element?
</details>
Done.

---

*[src/mapPrint.js, line 174 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KTorAUPYaxdz0FpkNV4:-KTpXC5YpImifTEMT3h7:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/3faddd1fc0c9bed44f6dcb0acd1606eee09cf44e/src/mapPrint.js#L174)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you split the return line the same way you used for `options` above?  Something like:
> ```text
> @return {Object} the result and status of the print call
>                         - complete [bool]: true if the call was successful, false otherwise
>                         - canvas [HTMLCanvasElement]: the canvas of the composite image (only set if complete is true)
>                         - error[?]: the error details / exception object (only set if complete is false)
> ```
</details>
Done.

---

*[src/mapPrint.js, line 206 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KToqWkgq1UYSqhmJQmE:-KTpYScYVBOVYQf01XJE:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/3faddd1fc0c9bed44f6dcb0acd1606eee09cf44e/src/mapPrint.js#L206)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> small style fix here and below `canvas: canvas` can be changed to `canvas` (it will automatically name the property with the same name in ES6)
> applies to `error: error` as well
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/mapPrint.js, line 121 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KTqCeL6ZorB5DV36t7r:-KTqCeL6ZorB5DV36t7s:biiut3b) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7727ba28f4ac8a331020c4261150c279abd9e3bc/src/mapPrint.js#L121)):*
> ```JavaScript
> * @param {Object} map esri map object
> * @return {Promise} resolving when the canvas have been created
> *                           resolve with a canva element with user added layer on it
> ```

typo: canvas

---

*[src/mapPrint.js, line 177 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KTqCYzO4cmjTBjAQAeP:-KTqCYzPzDyTOmwbtld4:b-vuo9m6) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7727ba28f4ac8a331020c4261150c279abd9e3bc/src/mapPrint.js#L177)):*
> ```JavaScript
> * @param {Object} esriBundle bundle of API classes
> * @param {Object} geoApi geoApi to determine if we are in debug mode
> @return {Object} the result and status of the print call
> ```

Missing the leading `* `

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-:-KTsoXyI39FZKXQ5CnJm:bnfp4nl)*

**Comment by jolevesq** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/mapPrint.js, line 121 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KTqCeL6ZorB5DV36t7r:-KTsraKYUBQOAwjDN8b5:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7727ba28f4ac8a331020c4261150c279abd9e3bc/src/mapPrint.js#L121)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: canvas
</details>
Done.

---

*[src/mapPrint.js, line 177 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156#-KTqCYzO4cmjTBjAQAeP:-KTsrb1XzwdDIIt41taM:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7727ba28f4ac8a331020c4261150c279abd9e3bc/src/mapPrint.js#L177)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Missing the leading `* `
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/156)*

**Pull request merged**
