### PR TITLE
Basic ESRI loader

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/7)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7)

**Comment by jolevesq** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 20 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7#-K0Wxd9ktyoPT7xo_HhC)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/abc3b5a476e49e9578dca6313653eb0a76b1252a/gulpfile.js#L20)):</sup>
Should we use a space between items in array (style guide 5.2)?


---

<sup>**[gulpfile.js, line 28 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7#-K0WxP-p4Yy7lXAXpCKX)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/abc3b5a476e49e9578dca6313653eb0a76b1252a/gulpfile.js#L28)):</sup>
Should we set a space after opening bracket and closing bracket (style guide 3.2)?


---

<sup>**[gulpfile.js, line 40 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7#-K0Wy5rwljxNEFYPqjwM)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/abc3b5a476e49e9578dca6313653eb0a76b1252a/gulpfile.js#L40)):</sup>
Space before and after + operator?


---

<sup>**[gulpfile.js, line 54 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7#-K0WyLAPvFGTgKwBCrGz)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/abc3b5a476e49e9578dca6313653eb0a76b1252a/gulpfile.js#L54)):</sup>
Space after opening and before closing brackets


---

<sup>**[src/index.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7#-K0WzEw4K2IUiu1KNKjs)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/abc3b5a476e49e9578dca6313653eb0a76b1252a/src/index.js#L15)):</sup>
Why do you put a space after function (in style guide 13.4)?


---

<sup>**[src/index.js, line 27 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7#-K0Wzvgv3YNXqQJWV_2W)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/abc3b5a476e49e9578dca6313653eb0a76b1252a/src/index.js#L27)):</sup>
Need a space after coma


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7)

**Comment by jolevesq** [comment]
Reviewed 2 of 4 files at r2.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7)

**Comment by alyec** [comment]
@jolevesq all the style errors should be patched -- I'm just going to acknowledge the comments that should be fixed now.


---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

<sup>**[src/index.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7#-K0WzEw4K2IUiu1KNKjs)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/abc3b5a476e49e9578dca6313653eb0a76b1252a/src/index.js#L15)):</sup>
This one is an exception to the style guide: https://gitter.im/fgpv-vpgf?at=55f85bf7fe4ca46810e1cc99


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7)

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7)

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/7)

**Pull request merged**
