### PR TITLE
refactor(geoApi): adopt arrow functions

### PR DESCRIPTION
**Pull request by james-rae**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/37)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/attribute.js, line 113 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/37#-K64vSC5QjPspB1q7KNS:-K64vSC6sOle4DjfEuTt:-864772277) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4f00ade2ebf00074652bdd41e21db54bf50d1ea3/src/attribute.js#L113)):*
No need for brackets with one argument.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/37)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/37)*

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/37)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/37)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/37)*

**Pull request merged**
