### PR TITLE
Projection module

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/26)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/proj.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/26#-K3z8j4bkZD689-AQMJR:-K3z8j4bkZD689-AQMJS:-2131179357) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e264cdf44468e793de1bdeb6769b9cc70cf5130f/src/proj.js#L18)):*
Should all the functions have proper comment blocks to allow API doc generation?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/26)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/proj.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/26#-K3z8j4bkZD689-AQMJR:-K3zC3g7fNJvIoF5-2IF:-1226296029) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e264cdf44468e793de1bdeb6769b9cc70cf5130f/src/proj.js#L18)):*
I don't think this one would get exposed via jsdoc since it's local to `localProjectExtent`.  That said I don't mind adding proper headers.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/26)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/proj.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/26#-K3z8j4bkZD689-AQMJR:-K3zDQWmEIuDFU629H6e:688313934) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e264cdf44468e793de1bdeb6769b9cc70cf5130f/src/proj.js#L18)):*
Gotcha.  I mistook the function header above as the file header.  So sure, no sweat for the internal functions.  I guess projectEsriExtentBuilder should have the doc as it's public

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/26)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/proj.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/26#-K3z8j4bkZD689-AQMJR:-K3zEuRKcroqUS1LyQmg:2088588817) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e264cdf44468e793de1bdeb6769b9cc70cf5130f/src/proj.js#L18)):*
The builder version is not public, the part it returns is.  I'm not 100% sure where the best place for the comment is, and what syntax to add to make sure jsdoc/dgeni parses it properly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/26)*

**Comment by spencerwahl** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/26)*

**Pull request merged**
