### PR TITLE
feat(layer): user file validation

### PR DESCRIPTION
**Pull request by james-rae**
basic validation of user file

* performs easy validations
* extracts fields
* extracts geometry
* returns data in more useful format (input is arraybuffer)

mocky tests coming later™

---
This change is [Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/88)

### CODE REVIEW

**Comment by alyec** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/layer.js, line 429 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88#-KCrZxzzy972EQMxALuu:-KCrZxzzy972EQMxALuv:618983876) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/54c2c08f73dbeb59be4adb44ef04f6dfc41d462f/src/layer.js#L429)):*
This covers off utf8, correct?  If so I think that's pretty safe (not to mention that if a file is loaded locally it can be pretty hard to tell the file encoding without extra info supplied).

---

*[src/layer.js, line 486 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88#-KCr_krlkJ41KuM7BQKH:-KCr_krlkJ41KuM7BQKI:254773451) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/54c2c08f73dbeb59be4adb44ef04f6dfc41d462f/src/layer.js#L486)):*
The answer is almost always yes (although I think in this case errors should be thrown as full exceptions instead of resolving with valid = false).

I think this would also benefit from having each fileHandler return a promise instead of having one giant promise scoping everything.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88)*

**Comment by james-rae** [comment]
*[src/layer.js, line 486 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88#-KCr_krlkJ41KuM7BQKH:-KCukkCxwyiPlsRl7I4H:-1078367860) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/54c2c08f73dbeb59be4adb44ef04f6dfc41d462f/src/layer.js#L486)):*
@aleksueir what works best for you in the failure case?

* boolean on result value set to false
* validation function barfs up an error
* promise rejects

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/layer.js, line 486 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88#-KCr_krlkJ41KuM7BQKH:-KCuy8tAZjGdagf4LVCx:911968502) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/54c2c08f73dbeb59be4adb44ef04f6dfc41d462f/src/layer.js#L486)):*
reject would work.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88#-:-KCvuzbtDj3YPcFpZBg-:1417088721)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/88)*

**Pull request merged**
