### PR TITLE
add overview map to geoApi: See testScalebar.html for demo

### PR DESCRIPTION
**Pull request by ec-dev**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/67)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mapManager.js, line 70 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/67#-K9YljU-F2nx6OJypTgw:-K9YljU-F2nx6OJypTgx:94230143) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e6cdcfb61a668951314770b6b982c39823aa4a5e/src/mapManager.js#L70)):*
console.warn  ?  for extra warning power!
not life-or-death, can be done later

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/67)*

**Comment by ec-dev** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mapManager.js, line 70 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/67#-K9YljU-F2nx6OJypTgw:-K9Yqb-N-uFB8NuWH9Qc:1435250225) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e6cdcfb61a668951314770b6b982c39823aa4a5e/src/mapManager.js#L70)):*
agreed, done, thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/67)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/67)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/67)*

**Pull request merged**
