### PR TITLE
Feature/render

### PR DESCRIPTION
**Pull request by james-rae**
Changes to attribute loading. Layer metadata and attributes are loaded on separate promises.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/105)

### CODE REVIEW

**Comment by cynngah** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/attribute.js, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGYTThA7q-u91aMryoH:-KGYTThA7q-u91aMryoI:406765887) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/db6ab9b23be22613c8a2cd6ff90eaf03c2079e76/src/attribute.js#L8)):*
Is there a sample missing between the two lines?

---

*[src/attribute.js, line 26 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGYThcPzoEPuf5EggP6:-KGYThcPzoEPuf5EggP7:-1650856481) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/db6ab9b23be22613c8a2cd6ff90eaf03c2079e76/src/attribute.js#L26)):*
Can we change this to DO NOT instead of AVOID.  I can't really see a good case for using .attribData since getAttribs is smart about caching results.

---

*[src/attribute.js, line 131 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGYU5f2IyS8JlYpPLpb:-KGYU5f2IyS8JlYpPLpc:-508009347) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/db6ab9b23be22613c8a2cd6ff90eaf03c2079e76/src/attribute.js#L131)):*
It seems like loadDataBatch should take a layerData object since we're pulling so many fields out of it.  Maybe a TODO for later refactoring?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by james-rae** [comment]
*[src/attribute.js, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGYTThA7q-u91aMryoH:-KGYW4t3d-ivL-Ryx-oH:1793169596) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/db6ab9b23be22613c8a2cd6ff90eaf03c2079e76/src/attribute.js#L8)):*
no :smile:   the bundle part is the start of the sample.  maybe I should drop the above line, it's redundant and is confusing at least one person.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by james-rae** [comment]
*[src/attribute.js, line 26 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGYThcPzoEPuf5EggP6:-KGYVsWrb7kO-6d5SGmx:2133985213) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/db6ab9b23be22613c8a2cd6ff90eaf03c2079e76/src/attribute.js#L26)):*
a difficult ask, but I think i can accommodate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by james-rae** [comment]
*[src/attribute.js, line 131 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGYU5f2IyS8JlYpPLpb:-KGYWOfLkhhnZGLTOxND:-1847332608) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/db6ab9b23be22613c8a2cd6ff90eaf03c2079e76/src/attribute.js#L131)):*
will add a comment.  this whole process will be refactored when we switch from deferred to promise, would be the ideal time to factor in that suggestion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by alyec** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/attribute.js, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGYTThA7q-u91aMryoH:-KGYX1LqQGVY81SNE3hc:1313381871) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/db6ab9b23be22613c8a2cd6ff90eaf03c2079e76/src/attribute.js#L8)):*
Or capitalize your sentences.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by james-rae** [comment]
*[src/attribute.js, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGYTThA7q-u91aMryoH:-KGYXT0fR0rt2MkHbBpn:1158614910) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/db6ab9b23be22613c8a2cd6ff90eaf03c2079e76/src/attribute.js#L8)):*
Sounds like a good task for Miles

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/attribute.js, line 33 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGlIKG0qXRg1fYP2J8Q:-KGlIKGAfPD6WLctAx6x:-558158878) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/540e02abbf0e4f31be26bdde34e0913b6bf9a16b/src/attribute.js#L33)):*
If `attribData` should not be accessed directly, maybe we can rename it to `_attribData` to indicate that it's a private property.

---

*[src/attribute.js, line 90 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGlJIYusqr_Vzh_6H5N:-KGlJIYusqr_Vzh_6H5O:224408370) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/540e02abbf0e4f31be26bdde34e0913b6bf9a16b/src/attribute.js#L90)):*
Maybe we can rename it because it's too similar to `layerId`, like `featureId` or something.

---

*[src/attribute.js, line 118 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGlKEzvx10fzongItfe:-KGlKEzvx10fzongItff:1415836842) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/540e02abbf0e4f31be26bdde34e0913b6bf9a16b/src/attribute.js#L118)):*
One less indent:

```js
if (layerPackage.attribData) {
    return layerPackage.attribData;
}

....

return layerPackage.attribData;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/attribute.js, line 33 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGlIKG0qXRg1fYP2J8Q:-KGlZov9OyzxBjuozW1I:-1504763431) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/540e02abbf0e4f31be26bdde34e0913b6bf9a16b/src/attribute.js#L33)):*
Good idea.

---

*[src/attribute.js, line 90 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGlJIYusqr_Vzh_6H5N:-KGlZV4h_QlzjQCiuOsl:322615155) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/540e02abbf0e4f31be26bdde34e0913b6bf9a16b/src/attribute.js#L90)):*
as discussed offline, will keep `layerId` and change `layerIdx` to `featureIdx`.  Will also change `featureId` in the client to be `featureIdx` to be consistent

---

*[src/attribute.js, line 118 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGlKEzvx10fzongItfe:-KGlcE2NL2b9V-Qy91kE:-1311268962) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/540e02abbf0e4f31be26bdde34e0913b6bf9a16b/src/attribute.js#L118)):*
sounds fair.  will trade an indent for a `return`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/attribute.js, line 90 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105#-KGlJIYusqr_Vzh_6H5N:-KGlcWNLFIn1FmSny00U:-510466975) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/540e02abbf0e4f31be26bdde34e0913b6bf9a16b/src/attribute.js#L90)):*
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/105)*

**Pull request merged**
