### PR TITLE
Symbology fetching

### PR DESCRIPTION
**Pull request by cynngah**
Fetch symbology based on layer and object id

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/99)

### CODE REVIEW

**Comment by james-rae** [comment]
Looks good.  just add that one nice comment

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/symbology.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQVmhb9HXx4UDCZKDi:-KFQVmhb9HXx4UDCZKDj:-1916199959) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/17acf828b9df745fbf007de41995bda5817e8cd2/src/symbology.js#L13)):*
as this is fairly non-standard, maybe a comment that you are getting the renderer class type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-:-KFQWKNJpfFnQCFVsax3:-33420196)*

**Comment by cynngah** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/symbology.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQVmhb9HXx4UDCZKDi:-KFQYzs1Td29wQ0xkSJL:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/17acf828b9df745fbf007de41995bda5817e8cd2/src/symbology.js#L13)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99)*

**Comment by spencerwahl** [comment]
Nice console logs :+1: :abc: 

---

Reviewed 1 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/symbology.js, line 14 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZWbz7MRxN8a-VldJ:-KFQZWbz7MRxN8a-VldK:-470516354) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L14)):*
const

---

*[src/symbology.js, line 15 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZYEMBGgKb5Grbuie:-KFQZYEMBGgKb5Grbuif:-470516354) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L15)):*
const

---

*[src/symbology.js, line 16 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZat2qmAujJkp3QG0:-KFQZat2qmAujJkp3QG1:-470516354) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L16)):*
const

---

*[src/symbology.js, line 170 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZhVEZFsVTxgXQImq:-KFQZhVF4ARd8pKkFxXT:-470516354) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L170)):*
const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-:-KFQZF89Rsjr0rpqangd:-1354105878)*

**Comment by cynngah** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/symbology.js, line 14 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZWbz7MRxN8a-VldJ:-KFQ_qB0V-tcFG7-h2gX:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L14)):*
Done.

---

*[src/symbology.js, line 15 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZYEMBGgKb5Grbuie:-KFQ_qRqGzf7zkV3cLzN:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L15)):*
Done.

---

*[src/symbology.js, line 16 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZat2qmAujJkp3QG0:-KFQ_qlRh4-Ffoo8Fa_3:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L16)):*
Done.

---

*[src/symbology.js, line 170 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZhVEZFsVTxgXQImq:-KFQ_r3yeg-ER2d8UCe1:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L170)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99)*

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/symbology.js, line 37 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZUQ9eeU_TIqPbC3P:-KFQZUQ9eeU_TIqPbC3Q:213536590) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/17acf828b9df745fbf007de41995bda5817e8cd2/src/symbology.js#L37)):*
style nitpick: arrow function (also below)

---

*[src/symbology.js, line 83 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZlr6aK4pGOfI17gu:-KFQZlr6aK4pGOfI17gv:-116569402) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L83)):*
These should be declared closer to the point of their use (I'm guessing this was ported from ES5 code)

---

*[src/symbology.js, line 169 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQ_F1akOFLrIK74NWb:-KFQ_F1akOFLrIK74NWc:-1089381235) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L169)):*
Maybe move this comment into a jsdoc header for the function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99)*

**Comment by cynngah** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/symbology.js, line 37 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZUQ9eeU_TIqPbC3P:-KFQfhsBZfZ0u5ATtQoY:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/17acf828b9df745fbf007de41995bda5817e8cd2/src/symbology.js#L37)):*
Done.

---

*[src/symbology.js, line 83 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQZlr6aK4pGOfI17gu:-KFQfiS-3HNiji4l-ViX:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L83)):*
Done.

---

*[src/symbology.js, line 169 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99#-KFQ_F1akOFLrIK74NWb:-KFQayEBr8eZ_oHJXYdt:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/4422ea2c9e17e64f01ca156dfcffcea6bfc13531/src/symbology.js#L169)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/99)*

**Pull request merged**
