### PR TITLE
fix(events): add return event object to access it from outside

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1858

## Description

When we create a evant, it is return to the caller so we can access it to e.g. remote it.

## Testing

In testEvents.html

## Documentation

Inline

## Checklist

- [x] `gulp test` succeeds without warnings or errors
- [***no release note tag for 1.1.6-1***] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/191)

### CODE REVIEW

**Comment by james-rae** [comment]
Looks like this solution only works if we have one handler coming in on the `handlers` param.  It is possible to have many.  Will put proposed solution adjustment over multiple comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/events.js, line 8 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGsnyTadYWZ8SJ1Nel:-KiGsnyTadYWZ8SJ1Nem:b-qk208o) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/src/events.js#L8)):*
> ```JavaScript
>  * @param {handlers} handlers is an object which contains all handlers needed
>  *
>  * @return {object} evt is the event created on the object
> ```

`@return {object} evt contains the events created on the object, keyed by same properties as handlers input`

Feel free to reword to your liking

---

*[src/events.js, line 11 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGrcuuWUNryQ0dtGTh:-KiGrcuv3AX-ohnrTWSL:bplx3bz) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/src/events.js#L11)):*
> ```JavaScript
>  */
> function wrapEvents(esriObject, handlers) {
>     var evt;
> ```

`const evt = {};`

---

*[src/events.js, line 18 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGruOcgSmMlRrudjNd:-KiGruOcgSmMlRrudjNe:b-g4zhyo) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/src/events.js#L18)):*
> ```JavaScript
>         // TODO: Validity checking on inputs for dojoName
>         // make dojo call
>         evt = esriObject.on(dojoName, (e) => {
> ```

`evt[ourEventName] = esriObject.on(dojoName, (e) => {`

---

*[test/testEvents.html, line 30 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGsCGkBlnEeES-SKcz:-KiGsCGlYts3_RRk7Xvg:b-eown5c) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/test/testEvents.html#L30)):*
> ```HTML
>             clickEvt = api.events.wrapEvents(map, { click: (clickEvent) => {
>                 console.log(clickEvent.mapPoint.x);
>                 clickEvt.remove();
> ```

`clickEvt.click.remove()`
to make it clearer, you could rename the var name to `evt`, so code would read `evt.click.remove()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-:-KiGskWVU_bjRm7JuUTG:bs3tauf)*

**Comment by james-rae** [comment]
For an example of what I'm talking about, see [this use of wrapEvents](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v1.6.1/src/app/geo/map.service.js#L766) . The current code would probably only return the handler for the `update-end` event, overwriting the four.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-:-KiGuGT8K6i_VIq-yE80:bcdfn9b)*

**Comment by jolevesq** [comment]
You are right, because of the loop it will overwrite the previous event. I did it too fast to make it work with my need. Good catch. I will resubmit a new version in a minute

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-:-KiGu_d6AB-h1y1yTVh4:bm1x5rf)*

**Comment by jolevesq** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/events.js, line 8 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGsnyTadYWZ8SJ1Nel:-KiGvE_liXw5xj4TefKN:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/src/events.js#L8)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`@return {object} evt contains the events created on the object, keyed by same properties as handlers input`

Feel free to reword to your liking
</blockquote></details>

Done.

---

*[src/events.js, line 11 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGrcuuWUNryQ0dtGTh:-KiGvFhE3GSmc1koB1D0:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/src/events.js#L11)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`const evt = {};`
</blockquote></details>

Done.

---

*[src/events.js, line 18 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGruOcgSmMlRrudjNd:-KiGvGwB0qcP1sT1woz5:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/src/events.js#L18)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`evt[ourEventName] = esriObject.on(dojoName, (e) => {`
</blockquote></details>

Done.

---

*[test/testEvents.html, line 30 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGsCGkBlnEeES-SKcz:-KiGvJ7UG4mgq7b3PASW:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/test/testEvents.html#L30)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`clickEvt.click.remove()`
to make it clearer, you could rename the var name to `evt`, so code would read `evt.click.remove()`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/events.js, line 11 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGrcuuWUNryQ0dtGTh:-KiGwd1ahVbGiOLM8GbX:bmaqvgn) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/src/events.js#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

use `const` :)  :'D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191)*

**Comment by jolevesq** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/events.js, line 11 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191#-KiGrcuuWUNryQ0dtGTh:-KiZreucH641qTrN80uM:bl190ld) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/13d285b0d9c9cb8ea8f8ffcf2110cf4bd97aefe7/src/events.js#L11)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

use `const` :)  :'D
</blockquote></details>

I don't know why but I was thinking we use var. Maybe it is because we use var in the hmtl... Should have look 2 line below and would have seen the const. I will push a new clean one :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/191)*

**Pull request merged**
