### PR TITLE
Allow for reloading promise if it fails the first time.

### PR DESCRIPTION
**Pull request by cynngah**
fgpv-vpgf/fgpv-vpgf/issues/685

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/127)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/attribute.js, line 125 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127#-KLGePua0PvxuHeNGkAD:-KLGePua0PvxuHeNGkAE:-715292158) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/cd30e3ed2ed89313fbe97ba96db0e4791af6a279/src/attribute.js#L125)):*
> ```JavaScript
>     */
>     function getAttribs() {
>         if (layerPackage._attribData && layerPackage.promiseStatus) {
> ```

Actually, this has potentially the same problem as https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/810#. Until `promiseStatus` is set to true, calls to `getAttribs` will trigger another round of attribute loading.

Instead of using a boolean flag to tell if attributes are downloaded, remove failed promise reference from `layerPackage` on `catch`. 
```js
defFinished
    .then(features => ..., 
    error => {
        delete layerPackage._attribData;
        reject(error);
    });
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127)*

**Comment by alyec** [comment]
Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127)*

**Comment by AleksueiR** [comment]
This PR seems to address https://github.com/fgpv-vpgf/fgpv-vpgf/issues/694 as well? If so, please include a reference in your commit message.

---

Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/mapManager.js, line 79 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127#-KLHF_n2375s4XsOO6VZ:-KLHF_n2375s4XsOO6V_:192113638) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e2bfe94810438b9118e0a32f5d2b883243415cb7/src/mapManager.js#L79)):*
> ```JavaScript
> 
>         // TODO: add code to setup scalebar
>         if ('scalebar' in settings) {
> ```

`settings.scalebar` for consistency.

---

*[src/mapManager.js, line 99 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127#-KLHFKm5tDD67YvK2Uh9:-KLHFKm5tDD67YvK2UhA:-1721373152) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/e2bfe94810438b9118e0a32f5d2b883243415cb7/src/mapManager.js#L99)):*
> ```JavaScript
> 
>         // Setup overview map
>         if (settings.overviewMap && settings.overviewMap.visible === true) {
> ```

You can drop `=== true`, it's superfluous.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127#-:-KLHFl_YlosT9tr84s9M:-500253547)*

**Comment by cynngah** [comment]
wasn't supposed to LOL I tried resetting but it added in that too. Just gonna close this and open another PR.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/attribute.js, line 125 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127#-KLGePua0PvxuHeNGkAD:-KLHFVICYz69eZVG94i0:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/cd30e3ed2ed89313fbe97ba96db0e4791af6a279/src/attribute.js#L125)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Actually, this has potentially the same problem as https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/810#. Until `promiseStatus` is set to true, calls to `getAttribs` will trigger another round of attribute loading.
> 
> Instead of using a boolean flag to tell if attributes are downloaded, remove failed promise reference from `layerPackage` on `catch`. 
> ```js
> defFinished
>     .then(features => ..., 
>     error => {
>         delete layerPackage._attribData;
>         reject(error);
>     });
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127#-:-KLHH0cFXRXfmdeKSvfy:523316525)*

**Comment by AleksueiR** [comment]
:+1:  :D

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/127#-:-KLHHOfNdK1jKTXDhYUA:1157575529)*

**Pull request closed without merging**
