### PR TITLE
Round values for csv if needed in validation

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2422

As title, round values to at most 6 digits after the decimal place if needed.
## Testing

Manually and please see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2422 for more info related to testing
## Documentation

NA
## Checklist

- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/269)

### CODE REVIEW

**Comment by james-rae** [comment]
This is fine for validating lat/long fields. My small concern is `findCandidates` is advertised as a generic testing function where any type of regex can be passed.  We have now introduced some very specific code to it.  E.g. what happens if someone in the future uses `findCandidates` against a text field?  If a row fails the non-rounded test, then the code tries to math some text, would an error occur?

Could be just a change of documentation / naming to make this function specific for testing lat/longs would be sufficient (we're not currently using it for anything else).

You can also claim I'm worrying over nothing.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/269#-:-KwLigA-gttcG6iOua8H:b-1si7vp)*

**Comment by barryytm** [comment]
Don't close it yet

**Comment by james-rae** [comment]
waiting for 2nd reviewer anyways. take your time

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/269#-:-KwM6O6TBnkD65T0Cns3:b-xplzqp)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/269#-:-KwZwk3nQsqulK1fTSJz:bnfp4nl)*

**Comment by AleksueiR** [comment]
Is this one good to merge?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/269#-:-KwjJCLqZ-dCQRlWHaSV:bsyekpg)*

**Pull request merged**
