### PR TITLE
feat(mapManager): add extent to mapManager

### PR DESCRIPTION
**Pull request by ec-dev**
add esri/geometry/Extent to mapManager
note: create geometry.js to place all geometry related type
 when usage of geometry related types increases.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/69)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/69)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/index.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/69#-K9mLMAJO1iyl54ROWtW:-K9mLMAKecCL9Ayv0ryO:-1319432720) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/cd8674be2ab77993398853ba6d65d4322a12f905/src/index.js#L47)):*
ALPHABET ORDER YO

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/69)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/69)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/69)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/69)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/69)*

**Pull request merged**
