### PR TITLE
Support basemap opacity per sublayer

### PR DESCRIPTION
**Pull request by james-rae**
## Description

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2463

Allows config to target the opacity of individual tiles in a basemap collection. Allows for fancy overlays.

## Testing

Tried out some modified configs. They looked lovely.

## Checklist

- [x] `gulp test` succeeds without warnings or errors
- [ ] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/299)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/299)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/299)*

**Comment by james-rae** [comment]
Don't pull until https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2728 is finished

---







*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/299#-:-LDMimi4EamlTg9f7SH8:b-si2lz9)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/299)*

**Pull request merged**
