### PR TITLE
Allow for reloading promise if it fails

### PR DESCRIPTION
**Pull request by cynngah**
fgpv-vpgf/fgpv-vpgf#685

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/129)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/129)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/attribute.js, line 152 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/129#-KLHPpKIl6oIn8gjRxUH:-KLHPpKIl6oIn8gjRxUI:978664837) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/299c8fbe12638c769fb0308be777bbc98cd2872b/src/attribute.js#L152)):*
> ```JavaScript
>                     console.warn('error getting attribute data for ' + layerData.load.layerUrl);
> 
>                     delete layerPackage._attribData;
> ```

Please, add a comment explaining `_attribData` is deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/129)*

**Comment by cynngah** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/attribute.js, line 152 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/129#-KLHPpKIl6oIn8gjRxUH:-KLHj4YaKe_CzBOo-XRv:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/299c8fbe12638c769fb0308be777bbc98cd2872b/src/attribute.js#L152)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Please, add a comment explaining `_attribData` is deleted.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/129)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/129)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/129#-:-KLLjQDnEphebqMUw23H:1417088721)*

**Pull request merged**
