### PR TITLE
feat(print): Create Map Image from Print Service and user added layer

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1157, #1160

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/155)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/mapPrint.js, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKekKj8-JNDPdl1oZb:-KTKekKj8-JNDPdl1oZc:b-ryee5b) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L2)):*
> ```JavaScript
> 'use strict';
> const canvg = require('canvg-origin');
> ```

Would it be possible to run two export tasks from two different viewer instances on a single page at the same time?

---

*[src/mapPrint.js, line 16 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKeRMK0ICDzn-hUggb:-KTKeRMK0ICDzn-hUggc:bqgawbi) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L16)):*
> ```JavaScript
>   * - `exportMap`
>   */
> ```

These elements will no be on the host page. You will need to make them manually using `document.createElement`.

---

*[src/mapPrint.js, line 173 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKfpxv8W5IE6s_GHFU:-KTKfpxwGnuvtR9K4y3C:bm6jjwn) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L173)):*
> ```JavaScript
>         return new Promise((resolve) => {
> 
>             // get the image from ther server first. We will use it size to offset the
> ```

Since we are always using 'MAP_ONLY' now, would it make sense to generate a canvas for user-added layers in parallel with the print task?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/index.js, line 82 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTK3kRidefO3zKcilby:-KTK3kRjM9ruyVqGLIAK:bftob62) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/index.js#L82)):*
> ```JavaScript
>         ['esri/tasks/query', 'Query'],
>         ['esri/tasks/QueryTask', 'QueryTask'],
>         ['esri/tasks/PrintTemplate', 'PrintTemplate'],
> ```

Can you move these to alphabetical order?

---

*[src/mapPrint.js, line 16 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKeRMK0ICDzn-hUggb:-KTKqZDePCI_tOUFObrl:b-1l5em8) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L16)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> These elements will no be on the host page. You will need to make them manually using `document.createElement`.
</details>
In addition to this can we create them during `printMap`?  For example maybe we add an id to the options taken by `printMap` and have it either use the id (so the burden is on the viewer to create the temp element) or `printMap` can create and destroy the node.  This would also help reduce global state.

---

*[src/mapPrint.js, line 125 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKYdF4zKZgGk-zK4zF:-KTKYdF5Nhx3Ad1a6yYm:bmub4qb) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L125)):*
> ```JavaScript
> 
>     // scale preserve is true
>     let offX = (mapExportImg.width - map.width) / 2;
> ```

I think all these `let`s can become `const`s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155)*

**Comment by jolevesq** [comment]
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/index.js, line 82 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTK3kRidefO3zKcilby:-KTOiz3fFvafuWBN5F0c:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/index.js#L82)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you move these to alphabetical order?
</details>
Done.

---

*[src/mapPrint.js, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKekKj8-JNDPdl1oZb:-KTOj1B2ifRS3E3CgDTJ:b-6o074n) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L2)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Would it be possible to run two export tasks from two different viewer instances on a single page at the same time?
</details>
I modified the sample and it works for more then one map on a single page and even if both print process are started at the same time.

---

*[src/mapPrint.js, line 16 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKeRMK0ICDzn-hUggb:-KTOyy_orpZX4OQb7WeQ:b-219byx) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L16)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> In addition to this can we create them during `printMap`?  For example maybe we add an id to the options taken by `printMap` and have it either use the id (so the burden is on the viewer to create the temp element) or `printMap` can create and destroy the node.  This would also help reduce global state.
</details>
I created the element inside the function. If i create them inside a function and dont add them to the DOM. Do i have to destroy them or they will be catch by the garbage collector? 

---

*[src/mapPrint.js, line 125 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKYdF4zKZgGk-zK4zF:-KTOjObRDWwq3nCHIuJ1:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L125)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think all these `let`s can become `const`s
</details>
Done.

---

*[src/mapPrint.js, line 173 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKfpxv8W5IE6s_GHFU:-KTOjQPxJSxYr-utv5p9:b-nkq429) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L173)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Since we are always using 'MAP_ONLY' now, would it make sense to generate a canvas for user-added layers in parallel with the print task?
</details>
We can't because when we launch print task, user added layer visibility must be false and when we create the user image, it must be true. When the user added layer is not visible there a tag style="display: none;", we can maybe play with this to mimic the visibility without having to deal with the real visibility from the viewer. I don't know if it worth the effort. I will also add a parameters for user added layer visibility because the function will need to turn them on and off on both cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/mapPrint.js, line 89 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTQ9g4x5wvLEbWskt5Y:-KTQ9g4yhkPbbA_awxNh:bqltmvv) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/79a38a81a177f468fe947cc58b8a167b28515a02/src/mapPrint.js#L89)):*
> ```JavaScript
> }
> 
> /**
> ```

I think this pair of functions can be collapsed a bit:

```js
function hideGraphicsLayers(map) {
  return map.graphicsLayerIds
    .map(layerId => map.getLayer(layerId))
    .filter(layer => layer.visible)
    .map(layer => {
      layer.setVisibility(false);
      return layer;
    });
}

function showLayers(layers) {
  layers.forEach(layer => layer.setVisibility(true));
}
```

---

*[src/mapPrint.js, line 151 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTQGHoQqgf_ZUZK18cm:-KTQGHoQqgf_ZUZK18cn:b-7s4sqq) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/79a38a81a177f468fe947cc58b8a167b28515a02/src/mapPrint.js#L151)):*
> ```JavaScript
>     return new Promise((resolve) => {
>         // create canvas element
>         let mapExportImgLocal = document.createElement('canvas');
> ```

const

---

*[src/mapPrint.js, line 154 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTQFk_qIFwLqtFZw5SX:-KTQFk_rmgfq0Tf4LDS1:bysle5) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/79a38a81a177f468fe947cc58b8a167b28515a02/src/mapPrint.js#L154)):*
> ```JavaScript
> 
>         // parse the svg
>         resolve(canvg(mapExportImgLocal, svgtext, {
> ```

Since the calling function doesn't care about the return value at the moment how about moving the resolve inside `renderCallback` and resolving with `mapExportImgLocal`.  This could be used by the caller instead of having to pass data through the `localCanvas` global.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/mapPrint.js, line 16 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKeRMK0ICDzn-hUggb:-KTTpx8CSGG3mqjGeAFg:bwjukti) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I created the element inside the function. If i create them inside a function and dont add them to the DOM. Do i have to destroy them or they will be catch by the garbage collector? 
</details>
No, I don't believe you need to explicitly destroy elements not added to the DOM.

---

*[src/mapPrint.js, line 173 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTKfpxv8W5IE6s_GHFU:-KTTqb0gOC3nfgdRY57M:bp8xger) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/d9368095f6c64cb20fd8beae36de6314dce25aaa/src/mapPrint.js#L173)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> We can't because when we launch print task, user added layer visibility must be false and when we create the user image, it must be true. When the user added layer is not visible there a tag style="display: none;", we can maybe play with this to mimic the visibility without having to deal with the real visibility from the viewer. I don't know if it worth the effort. I will also add a parameters for user added layer visibility because the function will need to turn them on and off on both cases.
</details>
I understand that we need to hide file-based layers to submit a print task, but do we need to wait for the print task to resolve before restoring the visibility of the file-based layers? If we don't need to wait, we can submit a print task, restore visibility, and render file-based layers while we wait for the print service to respond. This will shave off some time of the whole generation process. I think that's how it was implement in RAMP since when generating an export image, you would see file-based layers rendered before the service-based ones.

---

*[src/mapPrint.js, line 99 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155#-KTTs3br4fi5OgCCBKeD:-KTTs3br4fi5OgCCBKeE:b-s6o9kz) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/79a38a81a177f468fe947cc58b8a167b28515a02/src/mapPrint.js#L99)):*
> ```JavaScript
>     let layer;
>     let visLayers = [];
>     const layers = map.graphicsLayerIds;
> ```

Correct me if I'm wrong, but wouldn't this hide __all__ the Feature layers, - service- and file-based (I understand `graphicsLayerIds` are layers rendered as svg)?

Also, when hiding user-added layers, we really want to hide just the file-based once, since the print service can deal with the service-based user-added layers. Is this correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/155)*

**Pull request closed without merging**
