### PR TITLE
fix(geoapi): add geoJson id backup and id autonumbering

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
## Description
No records displaying in datatable for canada.json layer fgpv-vpgf/fgpv-vpgf#1273

## Testing
Test done manually with different kind of geoJSON files

## Checklist

- [x] `gulp test` succeeds without warnings or errors
- [x] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/176)

### CODE REVIEW

**Comment by james-rae** [comment]
Possible future enhancement -- add a check in case `origID` is also a field in the file (keep trying with `origID1`, `origID2`).  But I think we are ok for know, as this is an edge case.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/176#-:-KZ2hThfPIQQ_jlgNuJI:bcrok22)*

**Comment by milesap** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/176)*

**Comment by alyec** [comment]
`fix(geoapi)` isn't the correct scope, it should be `fix(layer)`
also, all the issues are in the fgpv repo so they have to be linked with the full fgpv-vpgf/fgpv-vpgf#1273 for the issue linking to work

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/layer.js, line 728 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/176#-KZ3ZbsrxEf5FmBF8NPz:-KZ3ZbsrxEf5FmBF8NQ-:b8c7o2n) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b07a849e7093934146e776457e50c11d36a834db/src/layer.js#L728)):*
> ```JavaScript
>     // 0 is not a valid object id
>     geoJson.features.forEach(function (val, idx) {
>         let idBckp = { origID: '' };
> ```

const (but this is the only change in the file, so feel free to merge without changing)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/176#-:-KZ3_DG1vwsZKdqNdrix:b-uhkhyb)*

**Comment by ChrisLatRNCan** [comment]
I'll do the change (commit and const), it's not a big deal. Thanks

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/176#-:-KZ7G9a3yvHwfEdpXTXn:bjxa9wv)*

**Comment by ChrisLatRNCan** [comment]
I changed a bit the name of the backup attribute name (IDgeoJSON). Even though there's still potential collision with existing key name, I think there's less risk than origID

**Comment by james-rae** [comment]
Nice.  Yeah, that would be a very obscure collision

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/176#-:-KZ7P7xKqImYzwZXW71A:b-6ttoiw)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/176)*

**Comment by ChrisLatRNCan** [comment]
*[src/layer.js, line 728 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/176#-KZ3ZbsrxEf5FmBF8NPz:-KZ7PvAYFnfeuAhQhQ6x:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b07a849e7093934146e776457e50c11d36a834db/src/layer.js#L728)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

const (but this is the only change in the file, so feel free to merge without changing)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/176)*

**Comment by ChrisLatRNCan** [comment]
Calm down Christian, too much button pushing in reviewable

**Pull request merged**
