### PR TITLE
Add jscs stylish to build process

### PR DESCRIPTION
**Pull request by jolevesq**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/3)

### CODE REVIEW

**Comment by alyec** [comment]
:+1: this is much nicer


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3#-K07yyyT-khlARQsvbCc)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/94fb28d0584a96ad909b43924ccb2c3bf14a6573/gulpfile.js#L18)):</sup>
with the new combined reporter do we still need a separate jshint fail or will it break properly?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3#-K07yyyT-khlARQsvbCc)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/94fb28d0584a96ad909b43924ccb2c3bf14a6573/gulpfile.js#L18)):</sup>
I made some test with jscs errors and jshint errors. It always break but with JSHINT failed message even if the error is JSCS. Is it ok?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3#-K07yyyT-khlARQsvbCc)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/94fb28d0584a96ad909b43924ccb2c3bf14a6573/gulpfile.js#L18)):</sup>
Yeah, I don't think there's any problem with that.  What I was asking about was if we still need `jshint.reporter('fail')` called since everything is combined.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3#-K07yyyT-khlARQsvbCc)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/94fb28d0584a96ad909b43924ccb2c3bf14a6573/gulpfile.js#L18)):</sup>
If i remove the reporter('fail'), the gulp check finish without an error even if there is errors. I would say we still need it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3#-K07yyyT-khlARQsvbCc)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/94fb28d0584a96ad909b43924ccb2c3bf14a6573/gulpfile.js#L18)):</sup>
:white_check_mark: just wanted to check if there was anything we could remove.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3#-K07yyyT-khlARQsvbCc)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/94fb28d0584a96ad909b43924ccb2c3bf14a6573/gulpfile.js#L18)):</sup>
What does the jscsStylish report do that jshint's reporter doesn't?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3#-K07yyyT-khlARQsvbCc)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/94fb28d0584a96ad909b43924ccb2c3bf14a6573/gulpfile.js#L18)):</sup>
I'm guessing you mean what does jscsStylish do that jscs' basic reporter doesn't.  And the answer is: it's *stylish* :smile:  (formatting looks better IMO).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3#-K07yyyT-khlARQsvbCc)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/94fb28d0584a96ad909b43924ccb2c3bf14a6573/gulpfile.js#L18)):</sup>
Ha-ha, I see. I thought it was doing something more complicated like combining with jshint output or something.
In this case, we should also add this jscs reporter to the viewer repo.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3#-K07yyyT-khlARQsvbCc)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/94fb28d0584a96ad909b43924ccb2c3bf14a6573/gulpfile.js#L18)):</sup>
It combine the jshint output with jscs output and style them the same way jshint-stylish does.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/3)

**Pull request merged**
