### PR TITLE
Dynamiclayer

### PR DESCRIPTION
**Pull request by cynngah**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/75)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/layer.js, line 390 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1amsu3GcjNCPDdiTY:-KA1amsu3GcjNCPDdiTZ:1357111154) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L390)):*
maybe rename to getFeatureInfoBuilder (and the function at the bottom becomes getFeatureInfo).  We're not getting dynamic layers anymore.

---

*[src/layer.js, line 392 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1aOGSO3BXuO4wOiHb:-KA1aOGSO3BXuO4wOiHc:-1964429375) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L392)):*
Fetches feature information, including geometry, from esri servers for feature layer

---

*[src/layer.js, line 394 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1abWLsFRy0MnOyz2G:-KA1abWLsFRy0MnOyz2H:-1994068943) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L394)):*
 objectId for feature to be retrived from a feature layer

---

*[src/layer.js, line 395 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1a5vxUZ7L4THsyRB2:-KA1a5vxUZ7L4THsyRB3:-1305787844) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L395)):*
resolves with feature information

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75)*

**Comment by alyec** [comment]
text(layer) -> docs(layer)

---

Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-:-KA1d2Al5a__WEo8CEtc:729966536)*

**Comment by james-rae** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/layer.js, line 390 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1amsu3GcjNCPDdiTY:-KA5UGMwPVk4lyk_SkNe:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L390)):*
Done.

---

*[src/layer.js, line 392 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1aOGSO3BXuO4wOiHb:-KA5UGsHlGPJ49RZuZmg:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L392)):*
Done.

---

*[src/layer.js, line 394 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1abWLsFRy0MnOyz2G:-KA5UHFwYZU-SR0GdJgq:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L394)):*
Done.

---

*[src/layer.js, line 395 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1a5vxUZ7L4THsyRB2:-KA5UHciCS04M_j7R345:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L395)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/layer.js, line 395 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1a5vxUZ7L4THsyRB2:-KA5W-3pWuO4Xjh_kuT7:-1966352887) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L395)):*
I'd also like a description (or link) for the resolved object

---

*[src/layer.js, line 414 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA5VkWseqPEzvPUMTr9:-KA5VkWseqPEzvPUMTrA:-1029771743) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fecd0f53c1f465f65eee52995c74d7a7b9e2a20a/src/layer.js#L414)):*
resolve doesn't have a return value

---

*[src/layer.js, line 417 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA5VsQPqUj0KPtqzIto:-KA5VsQPqUj0KPtqzItp:1639048206) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fecd0f53c1f465f65eee52995c74d7a7b9e2a20a/src/layer.js#L417)):*
`reject(error)` probably makes more sense (also no return value)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75)*

**Comment by cynngah** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/layer.js, line 395 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA1a5vxUZ7L4THsyRB2:-KA5opMcsPY4KClw1Bc2:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/7eeb95a2a662c354bef329f1b607bfdbfba0cb0b/src/layer.js#L395)):*
Done.

---

*[src/layer.js, line 414 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA5VkWseqPEzvPUMTr9:-KA5f1hdD00wSd15LehK:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fecd0f53c1f465f65eee52995c74d7a7b9e2a20a/src/layer.js#L414)):*
Done.

---

*[src/layer.js, line 417 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75#-KA5VsQPqUj0KPtqzIto:-KA5f1IZKEM3Dt-5pq2H:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/fecd0f53c1f465f65eee52995c74d7a7b9e2a20a/src/layer.js#L417)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/75)*

**Pull request merged**
