### PR TITLE
Esri projection module

### PR DESCRIPTION
**Pull request by cynngah**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/47)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 5 of 9 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47)*

**Comment by james-rae** [comment]
Reviewed 5 of 9 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47)*

**Comment by alyec** [comment]
Reviewed 5 of 9 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[spec/projSpec.js, line 61 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47#-K85WcRJ4M3hWkEDzP7a:-K85WcRJ4M3hWkEDzP7b:97546856) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/593f9c2acd3850fd81dcd4d19c08fb9400677240/spec/projSpec.js#L61)):*
you can reuse `makeFakeEsriExtent` from the test above, just pull it out of the unit test fixture and make it a general utility function

---

*[spec/projSpec.js, line 76 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47#-K85XOtEdudHdcEM7RQ9:-K85XOtEdudHdcEM7RQA:1341500477) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/593f9c2acd3850fd81dcd4d19c08fb9400677240/spec/projSpec.js#L76)):*
you might want to check that the functions are present (or just change the test description since the test is pretty trivial)

---

*[spec/projSpec.js, line 80 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47#-K85Xs8HXbGUK9_JUlvw:-K85Xs8HXbGUK9_JUlvx:1401508575) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/593f9c2acd3850fd81dcd4d19c08fb9400677240/spec/projSpec.js#L80)):*
I don't think this tests the esriService code since the first part of the test replaces it with a spy.  Using a spy for the ESRI projection calls probably makes more sense.

---

*[src/proj.js, line 87 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47#-K85YH4IGFMn1c55LrQq:-K85YH4IGFMn1c55LrQr:-843489554) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/593f9c2acd3850fd81dcd4d19c08fb9400677240/src/proj.js#L87)):*
This function should be pulled out of the module exports block and needs a jsdoc block

---

*[src/proj.js, line 90 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47#-K85YhAVqvBnZ2X9uRYY:-K85YhAVqvBnZ2X9uRYZ:-470516354) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/593f9c2acd3850fd81dcd4d19c08fb9400677240/src/proj.js#L90)):*
const

---

*[src/proj.js, line 93 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47#-K85Yi1FO6pPFae2psBC:-K85Yi1FO6pPFae2psBD:456133246) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/593f9c2acd3850fd81dcd4d19c08fb9400677240/src/proj.js#L93)):*
const and the URL should not be hardcoded

---

*[src/proj.js, line 109 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47#-K85Yx1otQmHjvtiaQgn:-K85Yx1otQmHjvtiaQgo:2101690223) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/593f9c2acd3850fd81dcd4d19c08fb9400677240/src/proj.js#L109)):*
might want to rename this so it's a bit more clear about what the function does (`esriProject`? or `esriServerProject` if we want to be really descriptive)

---

*[src/proj.js, line 111 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47#-K85YUd5lLt548zlZJoS:-K85YUd5lLt548zlZJoT:-491595484) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/593f9c2acd3850fd81dcd4d19c08fb9400677240/src/proj.js#L111)):*
We should probably move Point and SpatialReference to their own module.  Maybe leave a TODO for now and we can do that once we are using a few more ESRI geometry types.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/proj.js, line 88 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47#-K8PTD7qQ7iDMAy7lTj_:-K8PTD7qQ7iDMAy7lTja:-507084066) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/99ccef95bc30a7ec96d4d7f2d45b6721fc3d0706/src/proj.js#L88)):*
`on the client` -> `on the server`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/47)*

**Pull request merged**
