### PR TITLE
fix(filter) show undefined when bad renderer

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Replace undefine symbol by empty svg so we not have undefnied inside filters panel for symbol

## Testing

Visual

## Documentation

Inline

## Checklist

- [x] `gulp test` succeeds without warnings or errors
- [] release notes have been updated
- [x] all commit messages are descriptive and follow guidelines
- [x] PR targets the correct release version
- I will assign this PR to the primary reviewer

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/180)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/symbology.js, line 167 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180#-KbzVKwcayXH6Ev_Gbf0:-KbzVKwcayXH6Ev_Gbf1:b-2yxa8a) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b7ddf9c54b1a96d5c597d6d3d33836a3fca4f3b8/src/symbology.js#L167)):*
> ```JavaScript
>     }
> 
>     if (typeof svgcode === 'undefined') {
> ```

`svgcode` is set to an empty svg on this line: https://github.com/fgpv-vpgf/geoApi/blob/b7ddf9c54b1a96d5c597d6d3d33836a3fca4f3b8/src/symbology.js#L92

I think something sets `svgcode` to `undefined` in one of the cases.  The "undefined" check should be done in the switch cases above. This way there is no need to reset `svgcode` to an empty svg again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/symbology.js, line 167 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180#-KbzVKwcayXH6Ev_Gbf0:-Kbz_uL5BiFCpZsfXlwC:b-v27p80) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b7ddf9c54b1a96d5c597d6d3d33836a3fca4f3b8/src/symbology.js#L167)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`svgcode` is set to an empty svg on this line: https://github.com/fgpv-vpgf/geoApi/blob/b7ddf9c54b1a96d5c597d6d3d33836a3fca4f3b8/src/symbology.js#L92

I think something sets `svgcode` to `undefined` in one of the cases.  The "undefined" check should be done in the switch cases above. This way there is no need to reset `svgcode` to an empty svg again.
</blockquote></details>

Each case reset the svgcode value like ```svgcode = renderer.svgcode;``` for the case SIMPLE.  If for some reason, the svg is not good it will set it to undefined. I put my check at the end so I don't have to repeat it for all cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/symbology.js, line 167 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180#-KbzVKwcayXH6Ev_Gbf0:-Kc3HH67meqTZqeFX918:b-pf0y0t) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b7ddf9c54b1a96d5c597d6d3d33836a3fca4f3b8/src/symbology.js#L167)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Each case reset the svgcode value like ```svgcode = renderer.svgcode;``` for the case SIMPLE.  If for some reason, the svg is not good it will set it to undefined. I put my check at the end so I don't have to repeat it for all cases.
</blockquote></details>

Understood. But we can still avoid setting the empty svg twice: define the `svgcode` variable at the top of this function as simply `let svgcode;` so it starts as `undefined`, and set it to `svgjs(document.createElement('div')).svg();` if it checks out as `undefined` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/symbology.js, line 167 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180#-KbzVKwcayXH6Ev_Gbf0:-Kc41tWhJ2vn-yuQW7Eh:b-896fix) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b7ddf9c54b1a96d5c597d6d3d33836a3fca4f3b8/src/symbology.js#L167)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Understood. But we can still avoid setting the empty svg twice: define the `svgcode` variable at the top of this function as simply `let svgcode;` so it starts as `undefined`, and set it to `svgjs(document.createElement('div')).svg();` if it checks out as `undefined` here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/symbology.js, line 167 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180#-KbzVKwcayXH6Ev_Gbf0:-Kc4Arr7Jg7a2LRipk5g:bucd4da) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b7ddf9c54b1a96d5c597d6d3d33836a3fca4f3b8/src/symbology.js#L167)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I thought you were going to keep the `if (typeof svgcode === 'undefined') {` check after the switch to catch all the cases where scgcode might be set to undefined. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/symbology.js, line 167 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180#-KbzVKwcayXH6Ev_Gbf0:-Kc4I2Rp7m2OJknldhAw:bamdtwn) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b7ddf9c54b1a96d5c597d6d3d33836a3fca4f3b8/src/symbology.js#L167)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I thought you were going to keep the `if (typeof svgcode === 'undefined') {` check after the switch to catch all the cases where scgcode might be set to undefined. 
</blockquote></details>

My mistake, I resubmitted a new version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by james-rae** [comment]
*[src/symbology.js, line 165 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180#-Kc4OpmXOaSq9PIoQKV1:-Kc4OpmYbwawVqOlfauo:bweciob) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bbee74b7932b40dc30df1d53d9234354aa606a73/src/symbology.js#L165)):*
> ```JavaScript
> 
>     // make an empty svg graphic in case nothing is found to avoid undefined inside the filters
>     if (typeof svgcode !== 'undefined') {
> ```

Should this be `===` instead of `!==`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/symbology.js, line 165 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180#-Kc4OpmXOaSq9PIoQKV1:-Kc4V6QHESGdGUvKNlbF:b7cgxi9) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/bbee74b7932b40dc30df1d53d9234354aa606a73/src/symbology.js#L165)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Should this be `===` instead of `!==`?
</blockquote></details>

You are right... I am really not multitasking today. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/symbology.js, line 167 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180#-KbzVKwcayXH6Ev_Gbf0:-KcIS4bDjuGNJj4tWzMl:b-81yck5) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/b7ddf9c54b1a96d5c597d6d3d33836a3fca4f3b8/src/symbology.js#L167)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

My mistake, I resubmitted a new version
</blockquote></details>

Perfect, thanks :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/180)*

**Pull request merged**
