### PR TITLE
feat(attributes): scrape scale and geometry

### PR DESCRIPTION
**Pull request by james-rae**
Pull scale level to support scale dependency in viewer (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/552).
Add in geometry type, as was same block of code.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/112)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/112)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/112)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/112)*

**Comment by james-rae** [comment]
Closes https://github.com/fgpv-vpgf/geoApi/issues/98

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/112)*

**Pull request merged**
