### PR TITLE
config related update

### PR DESCRIPTION
**Pull request by ec-dev**
added helper function to create Extent from extent settings.
update config settings to match v1.1

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/76)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mapManager.js, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76#-KAK_09Ijw7QGrLs3p83:-KAK_09Ijw7QGrLs3p84:310486182) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/84810ff5dc447464b0e9a858b48171eeb488a6a5/src/mapManager.js#L138)):*
This might be better named as `getExtentFromJson`, also `geoApi` should have no knowledge of the viewer's configuration format (at least at a large scale, small stuff like parsing extents is fine IMO)

Also, tests?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by ec-dev** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mapManager.js, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76#-KAK_09Ijw7QGrLs3p83:-KAk4QcRvzqvAKl6QbQe:-499146009) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/84810ff5dc447464b0e9a858b48171eeb488a6a5/src/mapManager.js#L138)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by cynngah** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/76)*

**Pull request merged**
