### PR TITLE
Add templates for issues and PRs

### PR DESCRIPTION
**Pull request by alyec**
See https://github.com/blog/2111-issue-and-pull-request-templates

Opening the PR as a starting point for discussion.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/81)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/81)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/81#-KAp3JBEAqJFcht1ngJj:-KAp3JBEAqJFcht1ngJk:1213064743) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/497a03e4eeb3a6b039f7525676820228eb40a773/.github/PULL_REQUEST_TEMPLATE.md#L9)):*
`unit tests have been added or unnecessary` for style changes and the like

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/81)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/81)*

**Comment by ec-dev** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/81)*

**Comment by alyec** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/81)*

**Pull request merged**
