### PR TITLE
hilight layer support

### PR DESCRIPTION
**Pull request by james-rae**
Enhancements in support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/677

New things include

* Attribute loading
  * Generate and store legend from renderer with SVG icons
  * Enhance renderer to include svg icons for fast feature lookup
* Hilighting
  * Generate a graphic layer capable of displaying hilighted graphics, marker pins, and haze out background
  * Support functions for cloning active graphics and generating graphics from server geometry
* Projections
  * Local geometry projection
* Symbology
  * Remove symbolgy config, instead enhance existing renderer with symbology
  * Get a symbol for a specific feature
  * `getGraphicSymbol` and `getGraphicIcon` now share same graphic search routine
  * Convert SVG symbology generator to work off server JSON format, not client
  * Support for new Triangle symbol
  
  
@cynngah please don't pull this into the repo until I give the nod...it has breaking changes on the app, and would like the app PR to be close-to-ready before pulling this.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/124)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/hilight.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9QxeQy_Y7B5JnEgd0:-KK9QxeRqsSfF9qOGE2l:695322145) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

As a general note for later refactoring, I think hilight layer would be a good candidate for a custom class which internally proxies to ESRI's GraphicsLayer.

---

*[src/hilight.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9M8QwVACBXzomltdD:-KK9M8QwVACBXzomltdE:-1820329528) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L52)):*
> ```JavaScript
>         let id = 'rv_hilight';
>         let hazeOpac = 110;
>         let pinSymbol = {
> ```

Can pinSymbol be moved into a json file?

---

*[src/hilight.js, line 81 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9N-POqAO0uRElnTEW:-KK9N-POqAO0uRElnTEX:712477437) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L81)):*
> ```JavaScript
>         }
> 
>         const hgl = new esriBundle.GraphicsLayer({ id, visible: true });
> ```

There are a lot of `hgl.something =` calls.  Is this adding stuff directly to the ESRI Layer?

---

*[src/hilight.js, line 113 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9Oi67trru785rLQJ0:-KK9Oi67trru785rLQJ1:242135134) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L113)):*
> ```JavaScript
>                 hgl.remove(hgl._hilightGraphic);
>             } else {
>                 // first application of hilight. add haze background
> ```

Suggestion to add: "Add a haze background by creating a partially opaque layer for the whole map extent with some buffer.  This should go under the highlighted graphic to make it stand out."

---

*[src/hilight.js, line 114 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9Nb47mnwZBfv6fdbC:-KK9Nb47mnwZBfv6fdbD:1584377087) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L114)):*
> ```JavaScript
>             } else {
>                 // first application of hilight. add haze background
>                 const hazeJson = {
> ```

Another candidate for JSON constants file.

---

*[src/hilight.js, line 127 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9NNseE6troE26ieqz:-KK9NNseE6troE26ier-:965935623) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L127)):*
> ```JavaScript
>                 const haze = new esriBundle.Graphic(hazeJson);
>                 haze.setGeometry(hgl._map.extent.expand(1.5)); // expand to avoid edges on quick pan
>                 haze.haze = true;  // notifies layer to put this under any hilight graphics
> ```

Are there any other obvious names we can use to get away from `haze.haze`?

---

*[src/hilight.js, line 151 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9PMtepyUWUW1VluhE:-KK9PMtfCgJMgsFY_oAl:-2076093705) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L151)):*
> ```JavaScript
>             const g = e.graphic;
>             const dojoShape = g.getShape();
>             if (dojoShape) {
> ```

Is there a case where `g.getShape()` is expected to not return anything?

---

*[src/symbology.js, line 34 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9SDtj_KwcDCw3r40e:-KK9SDtj_KwcDCw3r40f:608782394) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L34)):*
> ```JavaScript
>     // quick lookup object of legend names to data URLs
>     const legendLookup = {};
>     legend.layers[0].legend.forEach(legItem => {
> ```

`legend.layers[0].legend` is a bit confusing, can you explain what is happening?

---

*[src/symbology.js, line 76 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9SwIkM7V8VsCEMzym:-KK9SwIkM7V8VsCEMzyn:1715067810) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L76)):*
> ```JavaScript
> * @param {Object} attributes object of feature attribute key value pairs
> * @param {Object} renderer an enhanced renderer (see function enhanceRenderer)
> * @return {Object} an object with useful data about the found  (imageUrl and symbol)
> ```

How about "an Object with `imageUrl` and `symbol` properties for the matched renderer"?

---

*[src/symbology.js, line 108 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9TKi4F5EvtdP9fkjJ:-KK9TKi4F5EvtdP9fkjK:-1173954505) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L108)):*
> ```JavaScript
> 
>             // search the value maps for a matching entry.  if no match found, use the default image
>             renderer.uniqueValueInfos.every(uvi => {
> ```

The `Array.find` way
```js
const uvi = renderer.uniqueValueInfos.find(uvi => uvi.value === graphicKey);
imageUrl = uvi.imageUrl || renderer.defaultImageUrl;
symbol = uvi.symbol || renderer.defaultSymbol;
```

---

*[src/symbology.js, line 125 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9UUP6QSLNAZLn6sRM:-KK9UUP6QSLNAZLn6sRN:-1097115409) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L125)):*
> ```JavaScript
> 
>         case CLASS_BREAKS:
> ```

```js
const gVal = attributes[renderer.field];
const lower = renderer.minValue;

imageUrl = renderer.defaultImageUrl;
symbol = renderer.defaultSymbol;
if (gVal < lower) { break; }

let minSplits = renderer.classBreakInfos.map(cbi => cbi.maxValue);
minSplits.splice(0, 0, lower-1); // put lower-1 at the start of the array and shift all other entries by 1
const cbi = renderer.classBreakInfos.find((cbi, index) => gVal > minSplits[index] && gVal <= cbi.maxValue);
if (!cbi) { break; }
imageUrl = cbi.imageUrl;
symbol = cbi.symbol;
```

---

*[src/symbology.js, line 287 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9iyf6U1RSHizq_40j:-KK9iyf6U1RSHizq_40k:-1930208397) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L287)):*
> ```JavaScript
>     svg.addProp('fill-rule', 'evenodd');
> }
> ```

general refactoring note, we can probably move a lot of the SVG manipulation into it's own file, preferably with no direct ESRI dependencies

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by james-rae** [comment]
Review status: 6 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/hilight.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9QxeQy_Y7B5JnEgd0:-KKAGNe7ap295MrDfgaU:659493590) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> As a general note for later refactoring, I think hilight layer would be a good candidate for a custom class which internally proxies to ESRI's GraphicsLayer.
</details>
Over my head, but have added it as a TODO

---

*[src/hilight.js, line 81 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9N-POqAO0uRElnTEW:-KKA9e1xsczYn84Mzc1L:160394146) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L81)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> There are a lot of `hgl.something =` calls.  Is this adding stuff directly to the ESRI Layer?
</details>
Yes

---

*[src/hilight.js, line 127 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9NNseE6troE26ieqz:-KK9lJkl2vz7YEqJ8pRh:-1868772524) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L127)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Are there any other obvious names we can use to get away from `haze.haze`?
</details>
In good news, Alex want's to move away from the blanket polygon haze and instead fade out items in the DOM.  So this will be short lived.

---

*[src/hilight.js, line 151 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9PMtepyUWUW1VluhE:-KK9lUp7m3pQX0_AmZYf:1463769002) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L151)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Is there a case where `g.getShape()` is expected to not return anything?
</details>
I was running into the issue when I was calling `getShape` in the function that adds things to the layer rather than in this `graphic-node-add` handler.  Inside the handler it may be ok (i.e. I would hope it is guaranteed added at this point).  I will try removing it.

---

*[src/symbology.js, line 76 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9SwIkM7V8VsCEMzym:-KK9mBdqQ7_zxcZ49zdZ:-1292716784) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L76)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> How about "an Object with `imageUrl` and `symbol` properties for the matched renderer"?
</details>
Yep.  Looks like i didn't finish the sentence :trophy: 

---

*[src/symbology.js, line 108 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9TKi4F5EvtdP9fkjJ:-KKAH-JzZySnij-MGGsj:860039632) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L108)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> The `Array.find` way
> ```js
> const uvi = renderer.uniqueValueInfos.find(uvi => uvi.value === graphicKey);
> imageUrl = uvi.imageUrl || renderer.defaultImageUrl;
> symbol = uvi.symbol || renderer.defaultSymbol;
> ```
</details>
Had to adjust, as sample code will be deference error in the not found case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/hilight.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9QxeQy_Y7B5JnEgd0:-KKAHbzXe-oXEakCP3_M:1315720947) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L1)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> Over my head, but have added it as a TODO
</details>
FYI see `LayerRecord` in the viewer for what I mean by proxying.  Those should move into geoApi at some point and the refactor would make sense to do at the same time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/hilight.js, line 99 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KKAWfxGuLZMtKWBQNgN:-KKAWfxGuLZMtKWBQNgO:-718963000) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/5b91d3772e67d67d8b8eb1872ba94347784a39e5/src/hilight.js#L99)):*
> ```JavaScript
> 
>             if (!Array.isArray(graphic)) {
>                 graphic = [graphic];
> ```

If you are reassigning graphic to an array it should probably be renamed to graphics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by james-rae** [comment]
*[src/hilight.js, line 99 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KKAWfxGuLZMtKWBQNgN:-KKAY3sQHFrqzaSbczwE:-4050085) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/5b91d3772e67d67d8b8eb1872ba94347784a39e5/src/hilight.js#L99)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> If you are reassigning graphic to an array it should probably be renamed to graphics.
</details>
attempt at laziness foiled again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 10 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/hilight.js, line 127 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9NNseE6troE26ieqz:-KKDtvuCMYIsIPuLLbVO:-382733163) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L127)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> In good news, Alex want's to move away from the blanket polygon haze and instead fade out items in the DOM.  So this will be short lived.
</details>
I tried something quickly and we can set opacity to all layers except for basemap (assuming basemap is always the first layer in the layers dom node) and hilight layer quite easily:
```css
.rv-esri-map .layersDiv > div:not(:first-child), .rv-esri-map .layersDiv > svg g:not(#rv_hilight_layer) {
    opacity: 0.35 !important;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by james-rae** [comment]
*[src/hilight.js, line 127 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9NNseE6troE26ieqz:-KKFHCxvgmVtVWysHZRq:264691845) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L127)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I tried something quickly and we can set opacity to all layers except for basemap (assuming basemap is always the first layer in the layers dom node) and hilight layer quite easily:
> ```css
> .rv-esri-map .layersDiv > div:not(:first-child), .rv-esri-map .layersDiv > svg g:not(#rv_hilight_layer) {
>     opacity: 0.35 !important;
> }
> ```
</details>
* Thanks for looking into this and providing samples
* I have no idea what that is (assuming CSS?) or how to apply it :trophy: 
* Some basemaps are composite, meaning they have multiple tile sets but appear as one item in the selector. We appear to have removed our sample one from `config.en-CA.json`, but you may want to test against a two-layer basemap

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by james-rae** [comment]
Review status: 9 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/hilight.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9M8QwVACBXzomltdD:-KKUpfz1mxQb_avRms6M:-1299657660) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L52)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can pinSymbol be moved into a json file?
</details>
done, thanks

---

*[src/hilight.js, line 113 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9Oi67trru785rLQJ0:-KKUphFjyhyq4_Goy2OH:-1299657660) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L113)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Suggestion to add: "Add a haze background by creating a partially opaque layer for the whole map extent with some buffer.  This should go under the highlighted graphic to make it stand out."
</details>
done, thanks

---

*[src/hilight.js, line 114 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9Nb47mnwZBfv6fdbC:-KKUpi54wxy7YxRrl_fH:-1299657660) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L114)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Another candidate for JSON constants file.
</details>
done, thanks

---

*[src/symbology.js, line 34 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9SDtj_KwcDCw3r40e:-KKUplk1TFWe81nFuxvg:-1299657660) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L34)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> `legend.layers[0].legend` is a bit confusing, can you explain what is happening?
</details>
done, thanks

---

*[src/symbology.js, line 125 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9UUP6QSLNAZLn6sRM:-KKUpmiHwX5qrEa410yG:-1299657660) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L125)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> ```js
> const gVal = attributes[renderer.field];
> const lower = renderer.minValue;
> 
> imageUrl = renderer.defaultImageUrl;
> symbol = renderer.defaultSymbol;
> if (gVal < lower) { break; }
> 
> let minSplits = renderer.classBreakInfos.map(cbi => cbi.maxValue);
> minSplits.splice(0, 0, lower-1); // put lower-1 at the start of the array and shift all other entries by 1
> const cbi = renderer.classBreakInfos.find((cbi, index) => gVal > minSplits[index] && gVal <= cbi.maxValue);
> if (!cbi) { break; }
> imageUrl = cbi.imageUrl;
> symbol = cbi.symbol;
> ```
</details>
done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by AleksueiR** [comment]
Review status: 9 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/hilight.js, line 127 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9NNseE6troE26ieqz:-KKhq1TgkdPsiUr2KNqN:-1855141542) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L127)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> * Thanks for looking into this and providing samples
> * I have no idea what that is (assuming CSS?) or how to apply it :trophy: 
> * Some basemaps are composite, meaning they have multiple tile sets but appear as one item in the selector. We appear to have removed our sample one from `config.en-CA.json`, but you may want to test against a two-layer basemap
</details>
We can apply this later, after this gets merged. Is there an issue about adding highlighting enhancements?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/proj.js, line 26 \[r7\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KKhqmPotceWwKh3b03o:-KKhqmPotceWwKh3b03p:-1756972786) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/93d4226553de04fd24772a476053513a808d8068/src/proj.js#L26)):*
> ```JavaScript
>  * @private
>  */
> function makeEpsgString(proj) {
> ```

`makeEpsgString` is probably a bad name for the new version.  `normalizeProj` maybe?  Anything which indicates this can return more than an EPSG?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by james-rae** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/proj.js, line 26 \[r7\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KKhqmPotceWwKh3b03o:-KKj7DKrFPrTchwbNB4k:-1299657660) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/93d4226553de04fd24772a476053513a808d8068/src/proj.js#L26)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> `makeEpsgString` is probably a bad name for the new version.  `normalizeProj` maybe?  Anything which indicates this can return more than an EPSG?
</details>
done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 10 files at r1, 2 of 5 files at r2, 1 of 3 files at r3, 1 of 2 files at r7, 2 of 3 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/hilight.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9QxeQy_Y7B5JnEgd0:-KKn4n5f7lQlVJ7mia-u:808673876) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/hilight.js#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> FYI see `LayerRecord` in the viewer for what I mean by proxying.  Those should move into geoApi at some point and the refactor would make sense to do at the same time.
</details>
Sounds logical.  Thank you!

---

*[src/symbology.js, line 287 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124#-KK9iyf6U1RSHizq_40j:-KKn4ruHglAVRlX9Qr4R:808673876) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/458637d18749457b42223c41a8f56f4f83553353/src/symbology.js#L287)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> general refactoring note, we can probably move a lot of the SVG manipulation into it's own file, preferably with no direct ESRI dependencies
</details>
Sounds logical.  Thank you!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Comment by cynngah** [comment]
Reviewed 4 of 10 files at r1, 2 of 5 files at r2, 1 of 3 files at r3, 2 of 3 files at r8, 2 of 2 files at r9.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/124)*

**Pull request merged**
