### PR TITLE
dgeni setup and module doc examples

### PR DESCRIPTION
**Pull request by ec-dev**
please ignore most of the files, as they are from fgpv dgeni setup. I re-use the style and structures.

I've modified the following files for geoAPI, but they will show up as new addition:
docs/config/processor/docMergeProcessor.js (added code to process ngDoc method for geoAPI)
docs/config/dgeni-config.js (modified for geoAPI)
docs/config/templates/gcNav.template.html (modified)
docs/config/templates/index.template.html (modified)
docs/config/templates/module.template.html (modified)
docs/config/templates/methods.template.html (new)
docs/content/developer-guid.md (new: copied James Wiki as a demo)
docs/content/getting_started.md

geoAPI specific:
gulpfile.js
package.json
src/basemap.js
src/mapManager.js

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/41)

### CODE REVIEW

**Comment by AleksueiR** [comment]
What's hammerjs and why do we need it?

---

Review status: 0 of 49 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-:-K7TY64SV_PbZaz2Hvvi:-1689817074)*

**Comment by alyec** [comment]
Also, can you clarify which sections of the PR need review?  Is everything under docs/* copied directly from dgeni or are there any local modifications you want reviewed before the PR goes in?

---

Reviewed 7 of 49 files at r1.
Review status: 7 of 49 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-:-K7TbcMC77XsQWgq1uOx:117467948)*

**Comment by ec-dev** [comment]
**hammer.js**
used by angular material doc site, I kept the SPA (index, js, css).. Will follow up to see if it can be removed.

**Files modified for geoAPI - The stuff that needs review**
docs/config/processor/docMergeProcessor.js (added code to process ngDoc method for geoAPI)
docs/config/dgeni-config.js (modified for geoAPI)
docs/config/templates/gcNav.template.html (modified)
docs/config/templates/index.template.html (modified)
docs/config/templates/module.template.html (modified)
docs/config/templates/methods.template.html (new)
docs/content/developer-guid.md (new: copied James Wiki as a demo)
docs/content/getting_started.md

**geoAPI specific files that needs review**
gulpfile.js
package.json
src/basemap.js
src/mapManager.js

**Note on docs folder**

Files that's copied from angular material is the docs/app/js/lib, docs/app/styles and some default templates such as common, base, componentGroup, constant-data.

Files created or customized for fgpv-vpgf and geoAPI (some are based on angular material doc site)

doc/app folder: 
doc/app/js/app.js
doc/app/partials/home.tmpl.html

doc/config folder:
doc/config/file-reader/mddoc.js
doc/config/processors/*
doc/config/tag-defs/index.js, mddoc.js, memberof.js

doc/templates folder:
doc/templates/mddoc/*
doc/templates/partials/*
doc/templates/gcMethod.template.html
doc/templates/gcNav.template.html
doc/templates/index.template.html
doc/templates/js.template.html
doc/templates/module.template.html
doc/config/dgeni-config.js

doc/content/developer-guide.md, getting-started.md

---

Review status: 7 of 49 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-:-K7U00eO2JVDS8W8QvC2:937080087)*

**Comment by ec-dev** [comment]
Is there any way I can pick files that does not need review from reviewable? The only thing I can find is to insert GENERATED FILE DO NOT EDIT on the file as a comment.

---

Review status: 6 of 49 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-:-K7UCrxXNuwnt6DyIdoz:-462533329)*

**Comment by AleksueiR** [comment]
Just mark the files we don't need to review as "reviewed" yourself.

---

Review status: 6 of 49 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-:-K7UEFL_NdqeMQU0oxU3:337551039)*

**Comment by ec-dev** [comment]
Good idea, those files that does not need to be reviewed is marked as "reviewed" by ec-dev account.
Thanks!

---

Reviewed 35 of 49 files at r1.
Review status: 41 of 49 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-:-K7WgWrZR-yCxLLPmp6P:-1274144754)*

**Comment by james-rae** [comment]
Reviewed 7 of 49 files at r1.
Review status: 48 of 49 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/app/partials/home.tmpl.html, line 4 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-K7WnDk7YwLlPw0xoi-T:-K7WnDk8vs6BxY1kRnQc:-1998478032) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/dee2e1f3d906dae72fe485c8479490593f9c5a04/docs/app/partials/home.tmpl.html#L4)):*
if this is public facing, we should probably drop the "awesome"

---

*[docs/content/developer-guid.md, line 1 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-K7Wnh_Ba2Jkc9wdKp_U:-K7Wnh_Ba2Jkc9wdKp_V:1895197222) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/dee2e1f3d906dae72fe485c8479490593f9c5a04/docs/content/developer-guid.md#L1)):*
file name is "guid" instead of "guide"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/mapManager.js, line 9 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-K7WoP_cVJqrVlywOZie:-K7WoP_dyvbXsTTu41Oa:1137784536) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/dee2e1f3d906dae72fe485c8479490593f9c5a04/src/mapManager.js#L9)):*
Missing BasemapControl property.  Should we just let the doc generator handle properties and not type them here? I don't know how djeni handles that

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41)*

**Comment by james-rae** [comment]
Reviewed 4 of 49 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mapManager.js, line 9 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41#-K7WoP_cVJqrVlywOZie:-K7Ww44gDusESoLGWjaL:-1206983695) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/dee2e1f3d906dae72fe485c8479490593f9c5a04/src/mapManager.js#L9)):*
BasemapControl property is returned by mapManager.setupMap(). The module.export only returns the Scalebar and setupMap function.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41)*

**Comment by alyec** [comment]
Reviewed 4 of 50 files at r1, 1 of 1 files at r2, 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/41)*

**Pull request merged**
