### PR TITLE
renderer to legend

### PR DESCRIPTION
**Pull request by james-rae**
exposes function that converts a renderer to a legend object

unit tests come later™

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/102)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[.jscsrc, line 98 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFxsvVM26sKo0iNF9p_:-KFxsvVM26sKo0iNF9pa:-510466975) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/.jscsrc#L98)):*
:+1: 

---

*[src/symbology.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFxtHaRgX1DSRHPs2ro:-KFxtHaRgX1DSRHPs2rp:-2082344221) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L15)):*
You can use accents:
```js
const emptySVG = `<svg xmlns='http://www.w3.org/2000/svg' width='32' height='32'></svg>`;
```

---

*[src/symbology.js, line 26 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFxy1jckKpS7yYPUTcU:-KFxy1jckKpS7yYPUTcV:1075415223) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L26)):*
Why not look up renderer type on the `serviceResult` when extracting service info like in here https://github.com/fgpv-vpgf/geoApi/blob/master/src/attribute.js#L169 ? Or is this just temporary?

---

*[src/symbology.js, line 649 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFxzdcEKdJqgLCEBp98:-KFxzdcEKdJqgLCEBp99:2111992343) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L649)):*
Why is this always 0?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/symbology.js, line 400 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFy0TwJhGicgXPQv93T:-KFy0TwJhGicgXPQv93U:1449807961) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L400)):*
There are several functions in the form:
```js
c = getGlyphCorners(symbol.size);
return `path with c values subbed`;
```
I think these can be refactored into `makePath(symbol, shape)` where shape is an enum picking from several path options

---

*[src/symbology.js, line 552 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFy16nBqb9BYmI5xUmM:-KFy16nBqb9BYmI5xUmN:1431785786) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L552)):*
Since this stuff all the args into an object literal how about inlining it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/symbology.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFxtHaRgX1DSRHPs2ro:-KFyGb_8fwmbflfue9fv:-491085185) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L15)):*
NICE!

---

*[src/symbology.js, line 26 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFxy1jckKpS7yYPUTcU:-KFyGnivAg6NFUKvHnoG:-583822060) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L26)):*
The renderer-to-legend code can be used against file based layers, which have no server endpoint.  The above code is only run against services, and does not depend on a renderer work.  Thats why two different ways to do the same thing.

---

*[src/symbology.js, line 400 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFy0TwJhGicgXPQv93T:-KFyHztdQ4GZJgf48Rpj:-2138882366) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L400)):*
I think I can make this work.  Reason I didn't originally was to keep a common interface with `makePathPath` for universal mapping in `makeGlyphSVG`.  But I believe I can take advantage of javascript ignoring extra function params.

---

*[src/symbology.js, line 552 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFy16nBqb9BYmI5xUmM:-KFyIVWRTQQ-j-c-JcOu:-1839635775) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L552)):*
assuming I'm understanding what you're suggesting...

seemed like more typing on the in-lining, in particular when the source variable had different names than the label properties below.   e.g.

`return newLegendItem('Error!', emptySVG, 'image/svg+xml');`

would become 

`return {label: 'Error!', imageData: emptySVG, contentType: 'image/svg+xml'};`

and also means the three properties (label, imageData, contentType) are hardcoded in multiple spots.

---

*[src/symbology.js, line 649 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFxzdcEKdJqgLCEBp98:-KFyJqSPmtKLdlGIYfD8:1574671952) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L649)):*
because we are always dealing with only one renderer, so always one item (index 0).  The only reason there is a `layers` property at all is to make the return value have the same structure you would get from an ESRI Legend service.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/symbology.js, line 26 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFxy1jckKpS7yYPUTcU:-KFyKkluQHgLCaDDepEN:1164185924) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L26)):*
:heavy_check_mark:  Makes sense.

---

*[src/symbology.js, line 649 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFxzdcEKdJqgLCEBp98:-KFyL00-4yRNGHxtkVK0:2127861865) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L649)):*
:heavy_check_mark: `

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/symbology.js, line 552 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFy16nBqb9BYmI5xUmM:-KFyMt2dialXqcnS6jJ0:-786180465) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L552)):*
How about combining with a refactor of `symbolToLegend`:

```js
symbolToLegend() {
  let imageData = emptySVG;
  let contentType = 'image/svg+xml';
  try {
    switch {
       case line:
          imageData = svgData;
          break;
       case picture:
         imageData = base64Data;
         contentType = symbol.contentType;
         break;
    }
  } catch (e) {
    label = 'Error';
  }
  return { label, imageData, contentType };
}
```

---

*[src/symbology.js, line 604 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFyO4B-gTbHRPfVUDws:-KFyO4B0Ku1UFBH_piAn:-1485872984) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L604)):*
Taking a second look at this: is failing semi-silently the best option?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/symbology.js, line 552 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFy16nBqb9BYmI5xUmM:-KFyd6y-gYWiMD6supcc:432021016) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L552)):*
I like it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102)*

**Comment by james-rae** [comment]
*[src/symbology.js, line 604 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFyO4B-gTbHRPfVUDws:-KFyehkbAWSvcDRCBIq6:1823171505) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L604)):*
Due to the high number of variations on symbols, I felt safer to show a blank legend item with an "error" text (and hope someone whines about it) than to have the entire thing crash.  In my limited testing I already encountered a number of weird cases I had to bugfix.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/symbology.js, line 604 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-KFyO4B-gTbHRPfVUDws:-KFyfLrgOQZ0JgrUR9g3:1605498549) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/05b5515c51f3529554faf297ef75fcda8d7133da/src/symbology.js#L604)):*
:white_check_mark: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102)*

**Comment by AleksueiR** [comment]
A belated question for sure, but why did you decide not to use some SVG library, like [svg.js](https://github.com/wout/svg.js) for example?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-:-KGDRk4V2ONvLSLcNP7l:712231966)*

**Comment by james-rae** [comment]
I did some looking around at the beginning, but everything I found was about animation and dom objects.  I just wanted strings.  I didn't find the one above.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-:-KGDUxQcYcbpciQkdTGb:328747234)*

**Comment by AleksueiR** [comment]
Fair enough.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/102#-:-KGDXgxGMTtYkpMW4alF:-1024557721)*

**Pull request merged**
