### PR TITLE
Set geometry type on file layer

### PR DESCRIPTION
**Pull request by james-rae**
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1166

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/158)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158#-KTxoJrx_il17kZBZomD:-KTxoJrx_il17kZBZomE:b-p0e6io) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2a8b5a363b23448c450e1ad2abfe4c8e1ec69ea6/package.json#L3)):*
> ```JSON
> {
>   "name": "geoApi",
>   "version": "1.0.6-2",
> ```

Can you change it to `1.0.6-3`?  I tagged the map export PR with that number (it was missing a version bump).

---

*[src/layer.js, line 880 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158#-KTxp066NrZOkFZ6G5W3:-KTxp066NrZOkFZ6G5W4:b-5y4bja) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2a8b5a363b23448c450e1ad2abfe4c8e1ec69ea6/src/layer.js#L880)):*
> ```JavaScript
>             }
> 
>             layer.geometryType = geometryType;
> ```

Maybe add a comment explaining why we are doing this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158#-KTxoJrx_il17kZBZomD:-KTy4K9dlN4Sdne9fANj:b5d25a5) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2a8b5a363b23448c450e1ad2abfe4c8e1ec69ea6/package.json#L3)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Can you change it to `1.0.6-3`?  I tagged the map export PR with that number (it was missing a version bump).
</details>
*I tagged the map export PR with `1.0.6-2` (it was missing a version bump).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158)*

**Comment by james-rae** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158#-KTxoJrx_il17kZBZomD:-KTy9P0QjXGzADf0ykMs:btkw2fc) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2a8b5a363b23448c450e1ad2abfe4c8e1ec69ea6/package.json#L3)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> *I tagged the map export PR with `1.0.6-2` (it was missing a version bump).
</details>
my bad for not checking github first. donethanks

---

*[src/layer.js, line 880 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158#-KTxp066NrZOkFZ6G5W3:-KTy9NNha6bw3rGXY8PC:b-mhsq5s) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/2a8b5a363b23448c450e1ad2abfe4c8e1ec69ea6/src/layer.js#L880)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Maybe add a comment explaining why we are doing this.
</details>
donethanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158#-:-KTyElLC_r1uZTWW5S-y:bnfp4nl)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/158)*

**Pull request merged**
