### PR TITLE
feat(geoApi): add attribute loader module

### LINKED ISSUE #23: Create attribute submodule in geoApi
* Requires issue #13 to be completed first
* filename `attribute.js`
* generate file and have appropriate file header comments.  See the [wiki](https://github.com/fgpv-vpgf/geoApi/wiki/How-to-Add-a-New-Section-to-geoApi) as an example of how a file should look.
* in `index.js`
    * ensure required ESRI API classes are defined in array `esriDeps`
    * ensure function `initAll` assigns the submodule to the return object

### PR DESCRIPTION
**Pull request by james-rae**
add functions to load attributes from ESRI Feature and Dynamic Map Service Layers

Closes #23, #24, #25

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/33)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/attribute.js, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g7kh6o8AwlZd5m8-c:-K5g7kh6o8AwlZd5m8-d:2116634314) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L5)):*
Are we using arrow functions in gapi?

---

*[src/attribute.js, line 82 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g8rSsHGFmQUYDuFFv:-K5g8rSsHGFmQUYDuFFw:1579106209) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L82)):*
It's recommended to always specify radix for `parseInt`.
[mdn parseInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#Description)

---

*[src/attribute.js, line 163 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g9bSR9i__NwCae6h9:-K5g9bSR9i__NwCae6hA:-413729316) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L163)):*
Is there a reason for not returning the promise right away? I don't think `resultProm` is used anywhere else.

---

*[src/index.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5gAI0-BspP73E1E-g2:-K5gAI00aoQnyQajzUDa:-510466975) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/index.js#L11)):*
:+1: 

---

*[testAttribute.html, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5gARTLSy8hAEo52Ush:-K5gARTLSy8hAEo52Usi:1873926201) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/testAttribute.html#L19)):*
Are these spaces mixed with tabs? :D

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/attribute.js, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g7kh6o8AwlZd5m8-c:-K5gBI5MgC3ywPow0LB7:-760155603) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L5)):*
I'm not because I have no idea how they work.  Alien code.  If this is important (?) I can learn & refactor everything. Will delay your nicer basemap :'D.  Let me know

---

*[src/attribute.js, line 82 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g8rSsHGFmQUYDuFFv:-K5gC3BEKCIDua3TUrEw:964368336) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L82)):*
Sounds good, will add it

---

*[src/attribute.js, line 163 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g9bSR9i__NwCae6h9:-K5gCGEAOu-fqm3Nji8f:1085362839) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L163)):*
Sounds good.  Cut & paste to avoid cyclomatic anger resulted in this unrequired variable

---

*[testAttribute.html, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5gARTLSy8hAEo52Ush:-K5gCWwUpX_Zt6k69NFu:-2073970710) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/testAttribute.html#L19)):*
the test pages are temporary and dont go through the gulp checks.  once aly shows us how to make proper test cases, they will be migrated and these pages deleted.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33)*

**Comment by ec-dev** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/attribute.js, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g7kh6o8AwlZd5m8-c:-K5gCNAjygnlKqQ5zRrw:-759886076) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L5)):*
Not yet, at least not on the stuff I checked in.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33)*

**Comment by ec-dev** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/attribute.js, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g7kh6o8AwlZd5m8-c:-K5gEFZauzuHlUxd2xA0:-1127088454) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L5)):*
[Arrow functions are easy.](https://babeljs.io/docs/learn-es2015/#arrows-and-lexical-this)
No, no delays to a new basemap! :) But maybe start using them in new code.

---

*[src/attribute.js, line 82 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g8rSsHGFmQUYDuFFv:-K5gEA71wZMFA0zQ9ZGh:-510466975) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L82)):*
:+1: 

---

*[src/attribute.js, line 163 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5g9bSR9i__NwCae6h9:-K5gE6xXfBv4up69C_Uh:-510466975) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/src/attribute.js#L163)):*
:+1: 

---

*[testAttribute.html, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33#-K5gARTLSy8hAEo52Ush:-K5gDycFxqFapxFyJcoO:-510466975) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/33c7754b200cd639df11cc5cd00ccacef8f5365c/testAttribute.html#L19)):*
:+1: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33)*

**Comment by cynngah** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/33)*

**Pull request merged**
