### PR TITLE
extent boundary check

### PR DESCRIPTION
**Pull request by james-rae**
Extent check and adjustment (stolen from RAMP1).

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1320

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/166)

### CODE REVIEW

**Comment by alyec** [comment]
This is easy to unit test (everything from the test page can probably be converted)

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVytIBSZLM0QkBvsF5L:-KVytIBTADkCkkqxkHdB:b-lo11ph) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/package.json#L3)):*
> ```JSON
> {
>   "name": "geoApi",
>   "version": "1.0.7-4",
> ```

This should be `1.1.0-1` I don't know why we've been bumping the patch version for all the new stuff we've been adding to the API but it's been going on too long.

---

*[src/mapManager.js, line 204 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVytfoigMiJVKA0L3h_:-KVytfojN-wmaHLoBrDq:b-6nn14y) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L204)):*
> ```JavaScript
> 
>     /**
>      * @ngdoc method
> ```

We will need to change to the same doc style we use in the viewer now that we are using plain jsdoc.

---

*[src/mapManager.js, line 207 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVyu18SnnTqueYqdSKz:-KVyu18SnnTqueYqdSL-:b-rqljnp) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L207)):*
> ```JavaScript
>      * @name checkBoundary
>      * @memberof mapManager
>      * Checks if the given extent is outside of the maximum extent. If it is,
> ```

This isn't entirely accurate.  `adjusted` is only true if the centre lies outside the max it doesn't reflect size changes or clips where the centre has not crossed the boundary.  I think it might be a good idea to name the function differently as well since it isn't doing a simple intersect.

---

*[src/mapManager.js, line 229 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVyusfmRJNzZSiKJ0pt:-KVyusfmRJNzZSiKJ0pu:b-ktz1w6) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L229)):*
> ```JavaScript
> 
>         // test if the center of our extent is outside of the boundary
>         if (center.y > maxExtent.ymax) {
> ```

This is the exact same code as the if below with x and y swapped:
```js
const clip = (mid, max, min, len) => (mid > max) ? { max, min: max - len } : (mid < min) ? { min, max: min + len } : null;

xcoords = clip(center.x, maxExtent.xmax, maxExtent.xmin, width);
if (xcoords) {
  flag = true;
  [newExtent.xmin, newExtent.xmax] = [xcoords.min, xcoords.max];
}

ycoords = clip(center.y, maxExtent.ymax, maxExtent.ymin, width);
if (ycoords) {
  flag = true;
  [newExtent.ymin, newExtent.ymax] = [ycoords.min, ycoords.max];
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-:-KVyz1n_Upjm4GJcgTXd:b9zxe9k)*

**Comment by AleksueiR** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/mapManager.js, line 228 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVzXEbWJqDKgIq23G8E:-KVzXEbWJqDKgIq23G8F:b-uxe9aj) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L228)):*
> ```JavaScript
>         const center = extent.getCenter();
> 
>         // test if the center of our extent is outside of the boundary
> ```

Can we check if the current extent and the boundary stop overlapping instead of detecting when a center point crosses the boundary? This lets the user to pan a little bit farther (say the user wants to see how "the area of interest" looks in a corner of the map and it won't be possible if checking for the center point). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166)*

**Comment by james-rae** [comment]
I actually started this, then realized I'd have to implement more of the [fake esri extent](https://github.com/fgpv-vpgf/geoApi/blob/v1.0.7-3/spec/mapManagerSpec.js#L23).  Not a big fan of writing fake code to a fake an API, re-implementing one that already exists.  Much prefer testing the real thing in the file.  Are we allowed to use the real API in unit tests?  The fake way I feel I'm not even testing my code.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVytIBSZLM0QkBvsF5L:-KW4qjIWrsfotSctd8Ph:bskow01) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/package.json#L3)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> This should be `1.1.0-1` I don't know why we've been bumping the patch version for all the new stuff we've been adding to the API but it's been going on too long.
</details>
`1.0.7-4` came from following the [versioning instructions](https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Refreshing-the-geoApi-Library#pick-a-new-version-number). Appears we are missing a time/person/event to determine when `a.b.c-x` gets rebranded to `a.b.c`, or bumped to `a.b+1.0`, for geoApi.

---

*[src/mapManager.js, line 204 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVytfoigMiJVKA0L3h_:-KW4qqsXPkgffjQdUMHB:bbescqh) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L204)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> We will need to change to the same doc style we use in the viewer now that we are using plain jsdoc.
</details>
these are in a few other spots.  will clean them all in a separate commit

---

*[src/mapManager.js, line 207 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVyu18SnnTqueYqdSKz:-KW4qwAvNvT1b_0Km5Js:b-kd9h87) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L207)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> This isn't entirely accurate.  `adjusted` is only true if the centre lies outside the max it doesn't reflect size changes or clips where the centre has not crossed the boundary.  I think it might be a good idea to name the function differently as well since it isn't doing a simple intersect.
</details>
will adjust the comment.  Can you let me know the name you want (so I don't have to change it a second time)?

---

*[src/mapManager.js, line 228 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVzXEbWJqDKgIq23G8E:-KW4r0ZmsII5m4NUPCIy:b64mjwk) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L228)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Can we check if the current extent and the boundary stop overlapping instead of detecting when a center point crosses the boundary? This lets the user to pan a little bit farther (say the user wants to see how "the area of interest" looks in a corner of the map and it won't be possible if checking for the center point). 
</details>
Don't think I understand the corner example.  You can get the corner in the center of your screen ok with current approach.  Doing a "no longer intersects" means you can fill you screen with naughty map except for a sliver of pleasant map. If users need to see farther than the max boundary, I would suggest the site owner increase the max boundary; also means I don't need to rewrite the guts.

---

*[src/mapManager.js, line 229 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVyusfmRJNzZSiKJ0pt:-KW4rDu30a_15PpuoYst:bdaybrf) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L229)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> This is the exact same code as the if below with x and y swapped:
> ```js
> const clip = (mid, max, min, len) => (mid > max) ? { max, min: max - len } : (mid < min) ? { min, max: min + len } : null;
> 
> xcoords = clip(center.x, maxExtent.xmax, maxExtent.xmin, width);
> if (xcoords) {
>   flag = true;
>   [newExtent.xmin, newExtent.xmax] = [xcoords.min, xcoords.max];
> }
> 
> ycoords = clip(center.y, maxExtent.ymax, maxExtent.ymin, width);
> if (ycoords) {
>   flag = true;
>   [newExtent.ymin, newExtent.ymax] = [ycoords.min, ycoords.max];
> }
> ```
</details>
I'll change it since you already did the work. But to be honest I find your version much harder to read -- I need to parse it in my head to figure out what it does.  function `clip` reads like `min max mid len mid len mid max max max mid min`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-:-KW4q_O2MxtG-DDViz_k:bvzqpdc)*

**Comment by alyec** [comment]
You can use the ESRI API in tests, but since it's a web call to load it's going to be slow and needs a DOM API of some sort.  If we had protractor running this would be a good use case.  However, I don't think there's too much to mock here: I see `getHeight`, `getWidth` and `getCenter` which are all one liners.  Another option is to pull out the clipping code into a separate function and test that part only.  I think it's perfectly reasonable to ignore testing the part that just pulls data out of ESRI objects into local vars.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVytIBSZLM0QkBvsF5L:-KW5G71KJuVo44H0k-Vz:b2h34ns) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/package.json#L3)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> `1.0.7-4` came from following the [versioning instructions](https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Refreshing-the-geoApi-Library#pick-a-new-version-number). Appears we are missing a time/person/event to determine when `a.b.c-x` gets rebranded to `a.b.c`, or bumped to `a.b+1.0`, for geoApi.
</details>
Yeah, the comment wasn't specifically directed at you, but I noticed that we had a bunch of releases where we've never changed the minor version despite changing the API.  We should change it now so hopefully we break the trend.

The "missing" person should be the person posting the release.  The instructions are: if the API changes it should be `a.(b+1).0` or if it's bugfix only (i.e. a drop in replacement) it should be `a.b.(c+1)`.

---

*[src/mapManager.js, line 207 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVyu18SnnTqueYqdSKz:-KW59OfETZAsCq_F4jf2:b-6lsjh7) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L207)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> will adjust the comment.  Can you let me know the name you want (so I don't have to change it a second time)?
</details>
I'm not sure, but something implying modification `clipBoundary`, `updateBoundary` or `enforceBoundary` come to mind.

---

*[src/mapManager.js, line 229 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVyusfmRJNzZSiKJ0pt:-KW59ZJxlK8zQoujjH3K:b-fkhg90) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L229)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> I'll change it since you already did the work. But to be honest I find your version much harder to read -- I need to parse it in my head to figure out what it does.  function `clip` reads like `min max mid len mid len mid max max max mid min`
</details>
How about this version?  Using `if`s instead of ternaries and always building a new extent from the result.

```js
const clip = (mid, max, min, mapMax, mapMin, len) => {
  if (mid > mapMax) {
    [max, min] = [mapMax, mapMax - len];
  } else if (mid < min) {
    [max, min] = [mapMin + len, mapMin];
  }
  return { max, min };
};

const clippedExtent = {};
[clippedExtent.xmax, clippedExtent.xmin] = clip(center.x, newExtent.xmax, newExtent.xmin, maxExtent.xmax, maxExtent.xmin, width);
[clippedExtent.ymax, clippedExtent.ymin] = clip(center.y, newExtent.ymax, newExtent.ymin, maxExtent.ymax, maxExtent.ymin, height);
flag = clippedExtent.equals(newExtent); // I assume ESRI has something which does this
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-:-KW591m6k7WsUhRh7Bk4:b-kbzb9a)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/mapManager.js, line 207 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVyu18SnnTqueYqdSKz:-KW8_B4Oauoc_fz_NNYJ:b-432py8) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L207)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I'm not sure, but something implying modification `clipBoundary`, `updateBoundary` or `enforceBoundary` come to mind.
</details>
`enforceBoudnary` or `annoyTheUser` :)

---

*[src/mapManager.js, line 228 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVzXEbWJqDKgIq23G8E:-KW8acYZNz_PT9AhhsdF:bliwkvd) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L228)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> Don't think I understand the corner example.  You can get the corner in the center of your screen ok with current approach.  Doing a "no longer intersects" means you can fill you screen with naughty map except for a sliver of pleasant map. If users need to see farther than the max boundary, I would suggest the site owner increase the max boundary; also means I don't need to rewrite the guts.
</details>
That's the whole point - if users need to see more of the map, they can't ask the map owner to increase (they can, but it probably won't happen). If we are limiting the users, lets do it in a less strict way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166)*

**Comment by james-rae** [comment]
Rather unfortunate we can't use the real API without all that extra stuff (makes the tests much more relevant, and thus me more inclined to put effort into doing them; plus gives us tests when we upgrade to new minor api release).  Though I'm not that concerned about "slowness", it loads pretty fast and the tests only run prior to a commit.  Probably easier if we haggle this out in the office.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/mapManager.js, line 228 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVzXEbWJqDKgIq23G8E:-KWA5SZFemmqD2raAlxL:bp5trb4) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L228)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> That's the whole point - if users need to see more of the map, they can't ask the map owner to increase (they can, but it probably won't happen). If we are limiting the users, lets do it in a less strict way.
</details>
This still sounds like identical cases to me. Ignoring implementation, the use case is "the user should only be looking at a given area of the map". 

Current implementation (center point) was likely chosen due to ease of implementation. It allows at most half a screen into the naughty areas of the map.  Your suggestion indicates the user would need to see more than that. My argument is that if the user had any business looking farther, the site author would have made the maximum extent larger.  

The feature is all about restriction.  If we are getting into semantics, the "proper" implementation would be never show any map outside of the map extent.  

But again, seems all relative to me.  The author sets the max extent that works for them.  Any change in logic is essentially equivalent to simply using a different max extent; and of course, I am for utilizing the configurable extent instead of re-doing code that already works.  We can white-board if it still doesn't make sense.

---

*[src/mapManager.js, line 229 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVyusfmRJNzZSiKJ0pt:-KWA5lAVNPU8M1hyUN6A:bz2yajd) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L229)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> How about this version?  Using `if`s instead of ternaries and always building a new extent from the result.
> 
> ```js
> const clip = (mid, max, min, mapMax, mapMin, len) => {
>   if (mid > mapMax) {
>     [max, min] = [mapMax, mapMax - len];
>   } else if (mid < min) {
>     [max, min] = [mapMin + len, mapMin];
>   }
>   return { max, min };
> };
> 
> const clippedExtent = {};
> [clippedExtent.xmax, clippedExtent.xmin] = clip(center.x, newExtent.xmax, newExtent.xmin, maxExtent.xmax, maxExtent.xmin, width);
> [clippedExtent.ymax, clippedExtent.ymin] = clip(center.y, newExtent.ymax, newExtent.ymin, maxExtent.ymax, maxExtent.ymin, height);
> flag = clippedExtent.equals(newExtent); // I assume ESRI has something which does this
> ```
</details>
Now I've made you re-write code that worked in the first place twice :trophy: works for me.  Looks like `Extent.contains()` will do the trick for the last line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-:-KWA5LGBb4iX4s7q3Gd4:bzbl2ss)*

**Comment by alyec** [comment]
I'm okay with the protractor route.  Also, I'm good with the PR as is right now provided that some form of automated tests (jasmine or protractor) are the next thing that goes in.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/mapManager.js, line 229 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVyusfmRJNzZSiKJ0pt:-KWA6twcoFyR44PwtHkk:b-6sagbi) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L229)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> Now I've made you re-write code that worked in the first place twice :trophy: works for me.  Looks like `Extent.contains()` will do the trick for the last line
</details>
Sounds good, but if you still feel like your version is more readable we can discuss before merging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-:-KWA64jlIngDcwjogc9q:b9bas0b)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/mapManager.js, line 228 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-KVzXEbWJqDKgIq23G8E:-KWDBWcQ6bxfXir8DVAJ:bcaamsa) ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/24ed19f9fd34cf13cd97d9c5be276c8d1a40940f/src/mapManager.js#L228)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> This still sounds like identical cases to me. Ignoring implementation, the use case is "the user should only be looking at a given area of the map". 
> 
> Current implementation (center point) was likely chosen due to ease of implementation. It allows at most half a screen into the naughty areas of the map.  Your suggestion indicates the user would need to see more than that. My argument is that if the user had any business looking farther, the site author would have made the maximum extent larger.  
> 
> The feature is all about restriction.  If we are getting into semantics, the "proper" implementation would be never show any map outside of the map extent.  
> 
> But again, seems all relative to me.  The author sets the max extent that works for them.  Any change in logic is essentially equivalent to simply using a different max extent; and of course, I am for utilizing the configurable extent instead of re-doing code that already works.  We can white-board if it still doesn't make sense.
</details>
Fair enough - the actual implementation is irrelevant. I do, however, think this restriction is not backed by any sensible use case and might be detrimental to the user's experience with the app.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166)*

**Comment by james-rae** [comment]
Will make an issue to add protractor support when we have the time

---

Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-:-KWiXNyLPVs7dcLQKg8E:bedp8us)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-:-KWicPTr2reEQQg9O07f:bnfp4nl)*

**Comment by james-rae** [comment]
Also closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1333

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166#-:-KWiideOpNPNSwqO8MjZ:bq8fl26)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/166)*

**Pull request merged**
