### PR TITLE
Dist packaging

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/geoapi/8)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8)

**Comment by AleksueiR** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8#-K1KKkfbQHgRyIGBNT1t)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/0baeeec52b4b77fdac406c956c4b4b1fed181abc/gulpfile.js#L43)):</sup>
Both `zip` and `tgz` tasks depend on `build`, so when running `dist`, `build` will be executed twice, right?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8#-K1KKkfbQHgRyIGBNT1t)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/0baeeec52b4b77fdac406c956c4b4b1fed181abc/gulpfile.js#L43)):</sup>
No, I checked and gulp seems to be smart about that.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8)

**Comment by AleksueiR** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

<sup>**[gulpfile.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8#-K1KKkfbQHgRyIGBNT1t)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/0baeeec52b4b77fdac406c956c4b4b1fed181abc/gulpfile.js#L43)):</sup>
Interesting, I wonder he it knows. Any documentation on that?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8#-K1KKkfbQHgRyIGBNT1t)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/0baeeec52b4b77fdac406c956c4b4b1fed181abc/gulpfile.js#L43)):</sup>
Closest is on the github site: https://github.com/gulpjs/gulp/blob/master/docs/API.md#deps but it's not very clear that dependencies are only evaluated once.  I found out by trial and error.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8)

**Comment by jolevesq** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8)

**Comment by AleksueiR** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

<sup>**[gulpfile.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8#-K1KKkfbQHgRyIGBNT1t)** ([raw file](https://github.com/fgpv-vpgf/geoapi/blob/0baeeec52b4b77fdac406c956c4b4b1fed181abc/gulpfile.js#L43)):</sup>
Alright, found more here: https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-tasks-in-series.md


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8)

**Comment by ec-dev** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/geoapi/8)

**Pull request merged**
